### PR TITLE
fix(api-extractor-model): resolve doc reference for classes with merged interfaces

### LINKED ISSUE #10223: Some link tags resolve as empty spans
### Which application is this bug report for?

Documentation

### Issue description

Ambiguous link tags don't resolve:
- Overloads
- Merged Interfaces

Some link tags don't have corresponding generated nodes.

Most evident in classes that inherit from [GuildChannel](https://discordjs.dev/docs/packages/discord.js/main/GuildChannel:Class#isDMBased), all "is" method summaries have missing doc links.

### Steps to Reproduce

Visit [Page](https://discordjs.dev/docs/packages/discord.js/main/GuildChannel:Class#isDMBased)

### Versions

main

### Issue priority

Low (slightly annoying)

### PR DESCRIPTION
**Pull request by Qjuh**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #10223

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: packages/api-extractor-model/src/model/ModelReferenceResolver.ts [hunk 1]
```diff
@@ -113,11 +113,19 @@ export class ModelReferenceResolver {
 			const memberSelector: DocMemberSelector | undefined = memberReference.selector;
 			if (memberSelector === undefined) {
 				if (foundMembers.length > 1) {
-					result.errorMessage = `The member reference ${JSON.stringify(identifier)} was ambiguous`;
-					return result;
+					const foundClass: ApiItem | undefined = foundMembers.find((member) => member.kind === ApiItemKind.Class);
```
Comment (Jiralite) [inline packages/api-extractor-model/src/model/ModelReferenceResolver.ts:116]: How come the type is explicitly defined here? It is already `ApiItem | undefined`, no?

Comment (Qjuh) [reply packages/api-extractor-model/src/model/ModelReferenceResolver.ts:116]: Convention in api-extractor, they explicitly define all their variable‘s types… though if I was to fully follow their convention I would omit the `| undefined` but that was too cursed even for my taste.

**Review by iCrawl — APPROVED** [review]
