### PR TITLE
fix: Wrong _patch call from GuildEmoji#edit and other issues

### LINKED ISSUE #2671: GuildEmojiRoleStore#set returns incomplete GuildEmoji Object
**Please describe the problem you are having in as much detail as possible:**

The GuildEmoji resolved after GuildEmojiRoleStore#set is missing its name property.
By extension this also affects  GuildEmojiRoleStore#add and  GuildEmojiRoleStore#remove

**Include a reproducible code sample here, if possible:**
```js
const updatedEmoji = await msg.guild.emojis.get('emoji-id').roles.set(['role-id']);
console.log(updatedEmoji)
```

Looks like it has to do with a wrong options object being passed to:<https://github.com/discordjs/discord.js/blob/717e7f094a0b30a88ec48b073373223861e87b12/src/stores/GuildEmojiRoleStore.js#L80>
As manually doing the GuildEmoji#edit works flawlessly

**Further details:**

- discord.js version: 12.0.0-dev at 717e7f094a0b30a88ec48b073373223861e87b12
- node.js version: 10.50
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
minor, inconvenient at best

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 717e7f094a0b30a88ec48b073373223861e87b12

### PR DESCRIPTION
**Pull request by KingDGrizzle**
**Please describe the changes this PR makes and why it should be merged:**
This PR fixes some issues that showed up in GuildEmoji, and closes #2671 

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/GuildEmoji.js [hunk 1]
```diff
@@ -22,21 +22,21 @@ class GuildEmoji extends Emoji {
...
      */
-    this.requiresColons = data.require_colons;
+    if (data.require_colons) this.requiresColons = data.require_colons;
 
     /**
      * Whether this emoji is managed by an external service
      * @type {boolean}
      */
-    this.managed = data.managed;
+    if (data.managed) this.managed = data.managed;
```
Comment (kyranet) [inline src/structures/GuildEmoji.js]: If data.managed is false, this won't set.

File: src/structures/GuildEmoji.js [hunk 2]
```diff
@@ -22,21 +22,21 @@ class GuildEmoji extends Emoji {
...
   _patch(data) {
-    this.name = data.name;
+    if (data.name) this.name = data.name;
 
     /**
      * Whether or not this emoji requires colons surrounding it
      * @type {boolean}
      */
-    this.requiresColons = data.require_colons;
+    if (data.require_colons) this.requiresColons = data.require_colons;
```
Comment (kyranet) [inline src/structures/GuildEmoji.js]: If data.require_colons is false, this won't set.

File: src/structures/GuildEmoji.js [hunk 3]
```diff
@@ -110,10 +110,11 @@ class GuildEmoji extends Emoji {
    *   .catch(console.error);
    */
   edit(data, reason) {
+    data.roles = data.roles ? data.roles.map(r => r.id ? r.id : r) : undefined;
```
Comment (kyranet) [inline src/structures/GuildEmoji.js]: 1. This shouldn't mutate the arguments (If I happened to Object.freeze the data, this would error). Instead, declare it as a variable (my suggestion is `roles`).
1. You can optimize the calback doing `r => r.id || r`
