### PR TITLE
fix(ApplicationCommandManager): explicitly allow passing builders to methods

### LINKED ISSUE #8208: Builders - Shlashs commands
### Which package is this bug report for?

builders

### Issue description

When it comes to making subcommands, we have an error that states that the subcommand needs a type.

### Code sample

```typescript
Documentation code :

const { SlashCommandBuilder } = require('@discordjs/builders');

const data = new SlashCommandBuilder()
	.setName('info')
	.setDescription('Get info about a user or a server!')
	.addSubcommand(subcommand =>
		subcommand
			.setName('user')
			.setDescription('Info about a user')
			.addUserOption(option => option.setName('target').setDescription('The user')))
	.addSubcommand(subcommand =>
		subcommand
			.setName('server')
			.setDescription('Info about the server'));
```

### Package version

13.8.0

### Node.js version

16.9

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, Message, Reaction

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
- Fixes #8208 
- Explicitly allow passing JSON-encodable items to `create()`, `edit()`, and `set()` - via `transformCommand()`
- Fixed the return type of the `transformCommand()` method (typings)
- Fixed the type of the `data` parameter on `edit()` of `GuildApplicationCommandManager`, which was missed in:
  - #8163

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/typings/index.test-d.ts [hunk 1]
```diff
@@ -171,6 +180,11 @@ client.on('ready', async () => {
   const guildCommandFromGlobal = await client.application?.commands.fetch(guildCommandId, { guildId: testGuildId });
   const guildCommandFromGuild = await client.guilds.cache.get(testGuildId)?.commands.fetch(guildCommandId);
 
+  await client.application?.commands.create(slashCommandBuilder);
+  await client.application?.commands.create(contextMenuCommandBuilder);
+  await guild.commands.create(slashCommandBuilder);
+  await guild.commands.create(contextMenuCommandBuilder);
```
Comment (vladfrangu) [inline packages/discord.js/typings/index.test-d.ts:186]: can you also add a test with editing?

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
