### PR TITLE
fix(REST): strip webhook tokens

### LINKED ISSUE #9415: Request route for interaction response deletions includes the token
### Which package is this bug report for?

rest

### Issue description

Follow-up of #9019, this time it's DELETE `/webhooks/:id/:token/@original`

### Code sample

```typescript
client.rest.on("response", req => console.log(req.route))
```

### Package version

1.7.0

### Node.js version

18.15.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by D4isDAVID**
**Please describe the changes this PR makes and why it should be merged:**

Strip the token from webhook routes.

Fixes #9415.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/rest/src/lib/RequestManager.ts [hunk 1]
```diff
@@ -509,7 +509,9 @@ export class RequestManager extends AsyncEventEmitter<RestEventsMap> {
 			// Strip out all ids
 			.replaceAll(/\d{17,19}/g, ':id')
 			// Strip out reaction as they fall under the same bucket
-			.replace(/\/reactions\/(.*)/, '/reactions/:reaction');
+			.replace(/\/reactions\/(.*)/, '/reactions/:reaction')
+			// Strip out webhook tokens
+			.replace(/\/webhooks\/:id\/[^/]+(?<slash>\/)?/, '/webhooks/:id/:token$<slash>');
```
Comment (ImRodry) [inline packages/rest/src/lib/RequestManager.ts:514]: There’s no need to use named groups imo, you can just use the regular $1

Comment (D4isDAVID) [reply packages/rest/src/lib/RequestManager.ts:514]: ESLint gave me a warning idk

Comment (ImRodry) [reply packages/rest/src/lib/RequestManager.ts:514]: Ahh ok then, that’s a new one

**Review by ckohen — CHANGES_REQUESTED** [review]
This actually does change behavior significantly in the supposedly impossible case where two webhooks share an id (since webhooks *can* be keyed on id + token). Notably this is how interaction followups work (using the application id instead of the interaction id). 

What you've done is put all interaction followup requests (with the same method) in the same bucket!

We kinda got lucky with our implementation that happened to split out handlers because the route was different (because it had token in it) rather than because the major id was different.

Bonus to handling this properly would be that we don't create a bunch of duplicate hash entries in our hash cache.

In addition to what you've done (which is in the section that makes a route more generic to match how discord hashes routes), you need to edit the regex used to match major ids to include webhook tokens, so that we don't lose the uniqueness.

File: packages/rest/src/lib/REST.ts [hunk 2]
```diff
@@ -434,16 +434,20 @@ export class REST extends AsyncEventEmitter<RestEventsMap> {
 			};
 		}
 
-		const majorIdMatch = /^\/(?:channels|guilds|webhooks)\/(\d{17,19})/.exec(endpoint);
+		const majorIdMatch = /(?:^\/webhooks\/(\d{17,19}\/[^/]+))|(?:^\/(?:channels|guilds|webhooks)\/(\d{17,19}))/.exec(
```
Comment (ckohen) [inline packages/rest/src/lib/REST.ts:437]:
```suggestion
		const majorIdMatch = /(?:^\/webhooks\/(\d{17,19}\/[^/?]+))|(?:^\/(?:channels|guilds|webhooks)\/(\d{17,19}))/.exec(
```

Shouldn't match query params either

File: packages/rest/src/lib/REST.ts [hunk 3]
```diff
@@ -434,16 +434,20 @@ export class REST extends AsyncEventEmitter<RestEventsMap> {
...
+			endpoint,
+		);
 
-		// Get the major id for this route - global otherwise
-		const majorId = majorIdMatch?.[1] ?? 'global';
+		// Get the major id or id + token for this route - global otherwise
+		const majorId = majorIdMatch?.[1] ?? majorIdMatch?.[2] ?? 'global';
```
Comment (ckohen) [inline packages/rest/src/lib/REST.ts:442]:
```suggestion
		const majorId = majorIdMatch?.[2] ?? majorIdMatch?.[1] ?? 'global';
```

Flipping these because the standard match will happen far more often and when matching a webhook it stops processing after the first match

File: packages/rest/src/lib/REST.ts [hunk 4]
```diff
@@ -434,16 +434,20 @@ export class REST extends AsyncEventEmitter<RestEventsMap> {
...
 
 		const baseRoute = endpoint
 			// Strip out all ids
 			.replaceAll(/\d{17,19}/g, ':id')
 			// Strip out reaction as they fall under the same bucket
-			.replace(/\/reactions\/(.*)/, '/reactions/:reaction');
+			.replace(/\/reactions\/(.*)/, '/reactions/:reaction')
+			// Strip out webhook tokens
+			.replace(/\/webhooks\/:id\/[^/]+/, '/webhooks/:id/:token');
```
Comment (ckohen) [inline packages/rest/src/lib/REST.ts:450]:
```suggestion
			.replace(/\/webhooks\/:id\/[^/?]+/, '/webhooks/:id/:token');
```

**Review by ckohen — CHANGES_REQUESTED** [review]

**Review by ckohen — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by suneettipirneni — APPROVED** [review]
