### PR TITLE
fix(guildmember): make `pending` nullable

### LINKED ISSUE #6546: Misleading `GuildMember#pending` boolean on partial guild members
**Please describe the problem you are having in as much detail as possible:**
On the `guildMemberUpdate` event when an uncached guild member does something (most notably: joining the server via passing Membership Screening), `oldMember.pending` is `false`. This is incorrect.

**Include a reproducible code sample here, if possible:**
1. Ensure a guild member has not passed Membership Screening in the guild
2. Start the bot up:

```JavaScript
const client = new (require("discord.js").Client)({
  partials: [
    "GUILD_MEMBER"
  ],
  intents: [
    "GUILDS",
    "GUILD_MEMBERS"
  ]
});

client.on("guildMemberUpdate", (oldMember, newMember) => console.log(oldMember.pending, newMember.pending));
client.login(token);
```

3. Have them pass Membership Screening or change their nickname or give them a role etc.

<details>
<summary>Response</summary>
Under the assumption this was the guild member passing Membership Screening:

```JavaScript
false false
```
</details>

I was using this event to detect who passed Membership Screening in a server for which the bot does not have the guild member cached, as I do something upon them passing said feature. I would rather discord.js not assure that the property is `false` in this scenario, but rather, have it as `null`!

**Further details:**

- discord.js version: 13.2.0-dev
- Node.js version: 16.6.1
- Operating system: macOS Big Sur 11.5.2
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: GUILD_MEMBER
- gateway intents: GUILDS, GUILD_MEMBERS
- other: none
- I have also tested the issue on latest main; Commit hash: b89280a1dd19513b06991aae1d3b720aa3a1c542

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #6546 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -1089,7 +1089,7 @@ export class GuildMember extends PartialTextBasedChannel(Base) {
   public readonly displayName: string;
   public guild: Guild;
   public readonly id: Snowflake;
-  public pending: boolean;
+  public pending: boolean | null;
```
Comment (DTrombett) [inline packages/discord.js/typings/index.d.ts:1092]: Shouldn't this be changed in `PartialGuildMember` instead as it's null only when partial?
https://github.com/discordjs/discord.js/blob/50c6ddf1dbcfb5fe740c3ac13a9c85b0ece66819/packages/discord.js/typings/index.d.ts#L4773

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
