### PR TITLE
fix(Client): Move client initialization code

### LINKED ISSUE #11180: ClientReady is called without user and application
### Which package is this bug report for?

discord.js

### Issue description

An error occurs at startup:
TypeError: Cannot read properties of null (reading 'displayName')

**The most important part**: bot should not be on any server

### Code sample

```typescript
const { Client, Events } = require('discord.js')
const { token } = require('./config.json')

const client = new Client({
	intents: []
})

client.once(Events.ClientReady, (client) => console.log(`${client.user.displayName} is ready!`))

client.login(token)
```

### Versions

discord.js - 15.0.0-dev.1760486511-25b22c67a
node.js  - v23.10.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

25b22c67a

### PR DESCRIPTION
**Pull request by vakiliner**
**Please describe the changes this PR makes and why it should be merged:**

Closes #11180

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/client/Client.js [hunk 1]
```diff
@@ -44,6 +45,8 @@ const BeforeReadyWhitelist = [
   GatewayDispatchEvents.GuildMemberRemove,
 ];
 
+let ClientUser;
```
Comment (vakiliner) [inline packages/discord.js/src/client/Client.js]: Should ClientUser be lazy loaded?

**Comment by Qjuh** [comment]
I'd say the better fix would be to move all the READY event handling into READY.js, not the other way around. Or at least the checkReady() call

**Comment by vakiliner** [comment]
> I'd say the better fix would be to move all the READY event handling into READY.js, not the other way around. Or at least the checkReady() call

I just noticed that the Ready event is async
None of the packet handlers are async, so calling this function won't be awaitable
While this can easily be fixed by adding "await" before "PacketHandlers[packet.t](this, packet, shardId);", but is it necessary?

**Comment by vakiliner** [comment]
> I'd say the better fix would be to move all the READY event handling into READY.js, not the other way around. Or at least the checkReady() call

I believe this was not added to READY.js on purpose because the handler is async

**Comment by Qjuh** [comment]
> > I'd say the better fix would be to move all the READY event handling into READY.js, not the other way around. Or at least the checkReady() call
> 
> I believe this was not added to READY.js on purpose because the handler is async

Since I was the one who wrote that I can assure you that's not the reason. In v14 the checkReady check is in READY.js; this was simply an oversight when adapting to the direct use of /ws and should be reverted to check in READY.js

adding await would be a good idea however, and then the checkReady check for READY event could be added to handlePacket instead. Similar to how it checks for GUILD_CREATE and _DELETE.

**Comment by vakiliner** [comment]
> In v14 the checkReady check is in READY.js

Then checkReady() was not async

File: packages/discord.js/src/client/websocket/handlers/READY.js [hunk 2]
```diff
@@ -23,4 +25,7 @@ module.exports = (client, { d: data }, shardId) => {
   } else {
     client.application = new ClientApplication(client, data.application);
   }
+
+  client.status = Status.WaitingForGuilds;
+  await client._checkReady();
```
Comment (Qjuh) [inline packages/discord.js/src/client/websocket/handlers/READY.js]: If we await the checkReady it should be done in `Client#handleMessage()`; the READY handler should not be async.

Comment (vakiliner) [reply packages/discord.js/src/client/websocket/handlers/READY.js]: I can't find `Client#handleMessage()`, did you mean `Client#_handlePacket()`?

**Comment by didinele** [comment]
was a little later than "tonight", but I got to it. we should be good :)
