### PR TITLE
fix(MessageReaction): `toJSON()` infinite recursion

### LINKED ISSUE #9067: MessageReaction/ReactionEmoji toJSON infinite loop
### Which package is this bug report for?

discord.js

### Issue description

Calling MessageReaction.toJSON causes an infinite loop if the reaction has an emoji property since the flatten logic will call ReactionEmoji.toJSON, which triggers MessageReaction.toJSON again since the emoji object has a reference back to the reaction.

This is the log
```
RangeError: Maximum call stack size exceeded
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:5)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at ReactionEmoji.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\ReactionEmoji.js:23:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at ReactionEmoji.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\ReactionEmoji.js:23:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
```

### Code sample

```typescript
client.on(Events.MessageReactionAdd, (reaction, user) => {
   console.log(reaction.toJSON())
})
```

### Package version

14.7.1

### Node.js version

18.12.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #9067

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

File: packages/discord.js/src/structures/MessageReaction.js [hunk 1]
```diff
@@ -117,6 +117,10 @@ class MessageReaction {
     return flatten(this, { emoji: 'emojiId', message: 'messageId' });
   }
 
+  valueOf() {
+    return this.id;
```
Comment (vladfrangu) [inline packages/discord.js/src/structures/MessageReaction.js:121]: This doesn't exist 🤔

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
