### PR TITLE
fix(GuildChannel): spread clone options to avoid infinite recursion

### LINKED ISSUE #5553: GuildChannel#clone exceeds maximum call stack when providing a CategoryChannel to the parent option
`GuildChannel#clone()` internally uses `Util#mergeDefault` to merge the provided options with that of the channel being cloned.
If a CategoryChannel is provided as the `parent` option, `Util.mergeDefault` detects this as an object and infinitely recurses into it. 

**Include a reproducible code sample here, if possible:**

```js
const category = message.guild.channels.cache.get("category_id");
message.channel.clone({ parent: category });
```

**Workaround**
Pass the Snowflake directly / `category.id`

**Further details:**

- discord.js version: 12.5.3
- Node.js version: N/A
- Operating system: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: N/A
- gateway intents: N/A
- other: N/A

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR resolves #5553 by spreading the clone options instead of using `Util.mergeDefault`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

File: src/util/Util.js [hunk 1]
```diff
@@ -307,16 +307,18 @@ class Util {
    * Sets default properties on an object that aren't already specified.
    * @param {Object} def Default properties
    * @param {Object} given Object to assign defaults to
+   * @param {number} [maxDepth=Infinity] The maximum depth to check properties for
    * @returns {Object}
    * @private
    */
-  static mergeDefault(def, given) {
+  static mergeDefault(def, given, maxDepth = Infinity) {
+    if (maxDepth < 0) return given;
```
Comment (vladfrangu) [inline src/util/Util.js:315]: Shouldn't this be `<=`?

**Review by iCrawl — APPROVED** [review]
