### PR TITLE
fix(ChannelStore): return existing DMChannels within add()

### LINKED ISSUE #3324: DM channels only cache 1 message
**Please describe the problem you are having in as much detail as possible:**
In a DM channel, there is only 1 message cached at any point in time.
This seems to be only occuring on master branch.

**Include a reproducible code sample here, if possible:**
Repeatedly evaluating this in a DM channel when there are messages being sent in it always return `1`:
```js
dmChannel.messages.size;
```

**Further details:**
- discord.js version: v12.0.0-dev (master branch)
- Node.js version: v12.3.1
- Operating system: Linux Mint 19.1 Tessa, xfce4 
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash: 405bdb5b558eff478d0bde739cee1ee8e40c330b

### LINKED ISSUE #3437: new DMChannel instance being created for every DM
**Please describe the problem you are having in as much detail as possible:**
Each DM has `channel` property referring to a different DMChannel instance, despite being in the same channel with the same channel ID. New DMChannel instances seem to be created for every DM.

**Include a reproducible code sample here, if possible:**
```js
const { Structures } = require('discord.js');

module.exports = Structures.extend('DMChannel', (DMChannel) => {
  class CoolerDMChannel extends DMChannel {
    constructor(...args) {
      super(...args);

      console.log('init dm', this.id);
    }
  }

  return CoolerDMChannel;
});
// every message now gives:
// init dm 522873632003981318 
// init dm 522873632003981318
```

**Further details:**
- discord.js version: latest master
- Node.js version: v11.14.0
- Operating system: Windows Vista
- Priority this issue should have – please be realistic and elaborate if possible: kinda big let's be real
- Also, message partials are turned on, internal sharding too. This issue never occurred on my test bot, just the main one (it's sharded, maybe that helps), just recently started happening on both.

Possibly related to (or causing) #3324 

- [x] I have also tested the issue on latest master, commit hash: 3fcc862c5fa336bb26c570655245d57e2e532f20

### PR DESCRIPTION
**Pull request by izexi**
Fixes #3324 and fixes #3437 

When ChannelStore#add() was being called for DMs [here](https://github.com/discordjs/discord.js/blob/master/src/client/actions/ChannelCreate.js#L10), the existing DM wouldn't be returned since `guild` param will be falsy
https://github.com/discordjs/discord.js/blob/3fcc862c5fa336bb26c570655245d57e2e532f20/src/stores/ChannelStore.js#L58-L61
This led to Channel.create() getting [called](https://github.com/discordjs/discord.js/blob/master/src/stores/ChannelStore.js#L63) where a new instance of a DMChannel was being [created](https://github.com/discordjs/discord.js/blob/master/src/structures/Channel.js#L99) everytime which explains #3437 and since its being initialised with an empty message store everytime, the initial message (which would have called createDM) will be added resulting in `dm.messages.size` always being 1 hence #3324 .

This PR simply just returns the DMChannel if it already exists.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/stores/ChannelStore.js [hunk 1]
```diff
@@ -55,8 +55,8 @@ class ChannelStore extends DataStore {
   add(data, guild, cache = true) {
     const existing = this.get(data.id);
     if (existing && existing._patch && cache) existing._patch(data);
```
Comment (MrJacz) [inline src/stores/ChannelStore.js]: this could be moved inside the other if block
