### PR TITLE
docs(ClientUser): fix shardId nullable

### LINKED ISSUE #6020: ClientUser properties shardID says it is nullable
**Please describe the problem you are having in as much detail as possible:**

In the ClientUser file the shardID properties say they are nullable in various jsdocs however in the typings file it does not.
The below jsdocs say it is nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L100-L107
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L130-L138

However, these in the same file say it cannot be nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L143-L150
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/src/structures/ClientUser.js#L168-L173

As well as in the typings file says they cannot be nullable
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L516-L527
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L4074-L4079
https://github.com/discordjs/discord.js/blob/374c779f7f8bbaa9bf06fa2b5b16f60da5095b5c/typings/index.d.ts#L2774-L2779
The above ActivityOptions interface also has readonly assigned to the number array while all the other typings for shardID number array do not.

I couldn't find anything in the discord documentation about it and didn't know whether it being nullable was correct or non-nullable so I made a bug report about it.

**Include a reproducible code sample here, if possible:** N/A

**Further details:**

- discord.js version: 13.0.0-dev (master)
- Node.js version: N/A
- Operating system: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- I have also tested the issue on latest master, commit hash: `374c779`

### PR DESCRIPTION
**Pull request by DTrombett**
fix #6020 

**Please describe the changes this PR makes and why it should be merged:**

This PR fixes some jsdocs where `shardId` was showed as nullable while it isn't, in fact, passing `null` as `shardId` throws a TypeError. However, it's still marked as optional and types are ok.

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

File: src/structures/ClientUser.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ class ClientUser extends User {
    * @property {PresenceStatusData} [status] Status of the user
    * @property {boolean} [afk] Whether the user is AFK
    * @property {ActivitiesOptions[]} [activities] Activity the user is playing
-   * @property {?(number|number[])} [shardId] Shard Id(s) to have the activity set on
+   * @property {number|number[]} [shardId] Shard Id(s) to have the activity set on
```
Comment (vladfrangu) [inline src/structures/ClientUser.js:106]:
```suggestion
   * @property {number|number[]} [shardId] Shard id(s) to have the activity set on
```

**Review by vladfrangu — CHANGES_REQUESTED** [review]
Consistency

File: src/structures/ClientUser.js (hunk 1 above)
Comment (DTrombett) [reply src/structures/ClientUser.js]: Done! 👍

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
