### PR TITLE
fix(InteractionCreateAction): Ensure text-based channel for caching messages

### LINKED ISSUE #7749: TypeError: Cannot read properties of undefined (reading '_add')
### Which package is this bug report for?

discord.js

### Issue description

```
     this.message = this.channel?.messages._add(data.message) ?? data.message;
                                          ^

 TypeError: Cannot read properties of undefined (reading '_add')
     at new MessageComponentInteraction (/home/stormbeatz/StormBeatz/node_modules/discord.js/src/structures/MessageComponentInteraction.js:27:42)
     at new ButtonInteraction (/home/stormbeatz/StormBeatz/node_modules/discord.js/src/structures/ButtonInteraction.js:9:1)
     at InteractionCreateAction.handle (/home/stormbeatz/StormBeatz/node_modules/discord.js/src/client/actions/InteractionCreate.js:67:25)
     at Object.module.exports [as INTERACTION_CREATE] (/home/stormbeatz/StormBeatz/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
```

I haven't had the chance to look into exactly how to reproduce this yet, but I'm fairly certain it has to do with the new VC text chats as it started happening around the same time.

I marked this as high priority as it causes the bot to crash.

### Code sample

_No response_

### Package version

discord.js@13.6.0

### Node.js version

v16.4.0

### Operating system

_No response_

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, DirectMessages

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Text-in-Voice channels are gradually rolling out. When an interaction from a component is received in such a channel, discord.js will crash as it attempts to cache the respective message as we do not provide a message cache for voice channels.

This has been resolved by verifying that the channel an interaction came from is text-based (if it is going to cache the respective message). This logic has been applied to message context menu command interactions too despite being currently unusable in text-in-voice channels, but it is better to be safe than sorry.

This pull request resolves #7749.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/client/actions/InteractionCreate.js [hunk 1]
```diff
@@ -29,6 +31,7 @@ class InteractionCreateAction extends Action {
             InteractionClass = UserContextMenuCommandInteraction;
             break;
           case ApplicationCommandType.Message:
+            if (c && !c.isTextBased()) return;
```
Comment (xMooddyy) [inline packages/discord.js/src/client/actions/InteractionCreate.js:34]:
```suggestion
            if (!c?.isTextBased()) return;
```

Shouldn't this also work?

**Review by xMooddyy — CHANGES_REQUESTED** [review]

File: packages/discord.js/src/client/actions/InteractionCreate.js (hunk 1 above)
Comment (Jiralite) [reply packages/discord.js/src/client/actions/InteractionCreate.js:34]: No. This will break functionality for applications without bots.

Comment (DTrombett) [reply packages/discord.js/src/client/actions/InteractionCreate.js:34]: I mean, why can't we use an optional chaining operator?

File: packages/discord.js/src/client/actions/InteractionCreate.js [hunk 2]
```diff
@@ -16,9 +16,11 @@ class InteractionCreateAction extends Action {
     const client = this.client;
 
     // Resolve and cache partial channels for Interaction#channel getter
-    this.getChannel(data);
+    const c = this.getChannel(data);
```
Comment (kyranet) [inline packages/discord.js/src/client/actions/InteractionCreate.js:19]: Please don't give variables a single-character name.

**Review by kyranet — CHANGES_REQUESTED** [review]
Just one thing

File: packages/discord.js/src/client/actions/InteractionCreate.js (hunk 2 above)
Comment (Jiralite) [reply packages/discord.js/src/client/actions/InteractionCreate.js]: Done with 822c96ce17ee684a45730d71a8c7a5e55e3d71d8!

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
