### PR TITLE
types(MessageEmbed): allow APIEmbed type

### LINKED ISSUE #6627: Bug: MessageEmbed not accepting a date string even though it would be possible to do so
### Issue description

1. Create an object that has a type of `APIEmbed` from `discord-api-types`
2. Supply it to the `MessageEmbed` constructor
3. Observe TypeScript error

This issue could easily be fixed by making the setup function accept strings too, but throw an error if the input is not a valid date string. I would gladly write it in.

### Codesample

```typescript
import {MessageEmbed} from "discord.js"
import {APIEmbed} from "discord-api-types"

const API = <APIEmbed>{} // this is wrong, but it still throws the same TS error
const Embed = new MessageEmbed(API)
```

### discord.js version

13.1.0

### Node.js version

16.6.2

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

_No response_

### Which gateway intents are you subscribing to?

None, this doesn't relate to gateway intents

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
This PR adds support for the APIEmbed type in the MessageEmbed constructor. The code didn't need to be updated as it already supported this type. Fixes #6627

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by xMooddyy — APPROVED** [review]

File: src/structures/MessageEmbed.js [hunk 1]
```diff
@@ -37,6 +30,10 @@ class MessageEmbed {
    * @property {Partial<MessageEmbedFooter>} [footer] The footer of this embed
    */
 
+  /**
```
Comment (SpaceEEC) [inline src/structures/MessageEmbed.js:33]: Please revert documenting the second parameter of the constructor, it's intentionally undocumented because it's only to be used internally (since Discord doesn't hold itself to the limitation it's imposing).

**Review by SpaceEEC — CHANGES_REQUESTED** [review]

File: src/structures/MessageEmbed.js (hunk 1 above)
Comment (ImRodry) [reply src/structures/MessageEmbed.js:34]: Addressed in https://github.com/discordjs/discord.js/pull/6629/commits/870d811245c0aa8a95ebd0543fbdca9412c0b735

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
