### PR TITLE
fix(Thread): make archive_timestamp not nullable

### LINKED ISSUE #5964: Thread channels have archivedAt and archivedTimestamp if they're not archived
**Please describe the problem you are having in as much detail as possible:**
Any ThreadChannel, not archived, has the `archivedAt` and `archiveTimestamp` properties set to the date of the thread creation. 

**Include a reproducible code sample here, if possible:**

```js
<Message>.startThread("Test", 60)
    .then(thread => console.log(thread.archivedAt, thread.archiveTimestamp))
    .catch(console.error);
```

**Further details:**

- discord.js version: 13.0.0-dev.5ad83a6a65e5944ceb3a41fee2df40ba1f5b03e4 (last dev version at the moment)
- Node.js version: 15.14.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Moderate as Threads are not fully released by Discord yet

**Relevant client options:**

- partials: MESSAGE, REACTION, USER, GUILD_MEMBER, CHANNEL
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

### PR DESCRIPTION
**Pull request by DTrombett**
fix #5964

**Please describe the changes this PR makes and why it should be merged:**
This PR makes `archivedTimestamp` and `archivedAt` not nullable as shown in [Discord API docs](https://discord.com/developers/docs/resources/channel#thread-metadata-object).

Since these properties indicate the date of the last archive status change and not only the last archived/unarchive date maybe we can change their actual names, but for now, I'll keep them.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/structures/ThreadChannel.js [hunk 1]
```diff
@@ -135,12 +135,13 @@ class ThreadChannel extends Channel {
   }
 
   /**
-   * The time the thread was last archived or unarchived at
-   * @type {?Date}
+   * The time when the thread's archive status was last changed
+   * <info>If the thread was never archived or unarchived, this is the same as {@link ThreadChannel#createdAt}</info>
```
Comment (DTrombett) [inline src/structures/ThreadChannel.js:139]: Should I divide this like `archiveTimestamp` even if it's in the characters limit?

**Comment by DTrombett** [comment]
I see that `archiveTimestamp` is not the same as `createdTimestamp` when the Thread is not archived so I'll change the info block.

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
