### PR TITLE
Skip sweeping if the guild is not available

### LINKED ISSUE #10069: Cannot destructure property 'cache' of 'guild[key]' as it is undefined.
### Which package is this bug report for?

discord.js

### Issue description

[This](https://github.com/discordjs/discord.js/pull/7213) was seemingly fixed before, but I've noticed it happening again recently. I can't seem to reliably reproduce it but after running my bot for a certain amount of time, it'll pop up as an uncaught exception. ~~I'm not 100% sure if it's directly related to Stickers only or it just happens to happen with stickers.~~ Seems to be happening with emojis as well. I double checked all my guilds to see if they had those properties and they did, so it seems to be a timing issue.
```js
TypeError: Cannot destructure property 'cache' of 'guild[key]' as it is undefined.
    at Sweepers._sweepGuildDirectProp (/app/node_modules/discord.js/src/util/Sweepers.js:411:15)
    at Sweepers.sweepEmojis (/app/node_modules/discord.js/src/util/Sweepers.js:106:17)
    at Timeout._onTimeout (/app/node_modules/discord.js/src/util/Sweepers.js:462:21)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
```js
TypeError: Cannot destructure property 'cache' of 'guild[key]' as it is undefined.
    at Sweepers._sweepGuildDirectProp (/app/node_modules/discord.js/src/util/Sweepers.js:411:15)
    at Sweepers.sweepStickers (/app/node_modules/discord.js/src/util/Sweepers.js:212:17)
    at Timeout._onTimeout (/app/node_modules/discord.js/src/util/Sweepers.js:462:21)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### Code sample

```typescript
const getComparisonTimestamp = (e: any) => e?.createdTimestamp ?? lastFilterTimestamp;
const discordCacheItemsWeDontWant = {
    interval: intervalDefaultInSec,
    filter: Discord.Sweepers.filterByLifetime({
        lifetime: 5,
        getComparisonTimestamp
    })
} as Discord.SweepOptions<string, any>;

let mybot: Discord.Client;
const defaultClientOptions = {
    intents: [
        Discord.IntentsBitField.Flags.Guilds,
        Discord.IntentsBitField.Flags.GuildMembers,
        Discord.IntentsBitField.Flags.GuildVoiceStates,
        Discord.IntentsBitField.Flags.GuildPresences,
        Discord.IntentsBitField.Flags.GuildEmojisAndStickers,
        Discord.IntentsBitField.Flags.GuildMessages,
        Discord.IntentsBitField.Flags.MessageContent,
        Discord.IntentsBitField.Flags.DirectMessages,
        Discord.IntentsBitField.Flags.GuildMessageReactions
    ],
    partials: [
        Discord.Partials.Channel,
        Discord.Partials.Reaction,
        Discord.Partials.GuildMember,
        Discord.Partials.Message
    ],
    rest: {
        offset: 250,
        retries: 10
    },
    closeTimeout: 10000,
    makeCache: Discord.Options.cacheEverything(),
    sweepers: {
        ...Discord.Options.DefaultSweeperSettings,
        messages: discordCacheItemsWeDontWant,
        emojis: discordCacheItemsWeDontWant,
        reactions: discordCacheItemsWeDontWant,
        stageInstances: discordCacheItemsWeDontWant,
        invites: discordCacheItemsWeDontWant,
        bans: discordCacheItemsWeDontWant,
        stickers: discordCacheItemsWeDontWant,
        threads: discordCacheItemsWeDontWant,
        threadMembers: discordCacheItemsWeDontWant
    }
} as Discord.ClientOptions;
```

### Versions

discord.js: 14.14.1
node: 21.4.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildPresences, GuildMessages, DirectMessages, MessageContent

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by JMTK**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #10069. It would seem that certain properties do not get set properly if the guild is not available, so when we go to sweep them, the property is undefined (.stickers, .emojis etc). Skipping unavailable guilds on a sweep pass should resolve the issue.

**Status and versioning classification:**
Patch

### CODE REVIEW

File: packages/discord.js/src/util/Sweepers.js [hunk 1]
```diff
@@ -425,6 +425,9 @@ class Sweepers {
     let items = 0;
 
     for (const guild of this.client.guilds.cache.values()) {
+      // We may be unable to sweep the cache if the guild is unavailable
+      if (!guild.available) continue;
```
Comment (Qjuh) [inline packages/discord.js/src/util/Sweepers.js:429]: I know I proposed this as one of two possible fixes. But after thinking about it it seems that the fix to have a fallback in the next line if `guild[key]` was undefined would be the better alternative, because we‘d still want to sweep caches of unavailable guilds if the cache exists. So `if (!(key in guild))` seems to be the better option imho.

Comment (JMTK) [reply packages/discord.js/src/util/Sweepers.js:429]: Makes sense! Pushed a fix

**Comment by JMTK** [comment]
BTW I was able to test/reproduce this by lowering my sweep interval to 1s, which was too soon before the bot was able to login and I got the same error. Seems fine after

**Review by Qjuh — APPROVED** [review]

File: packages/discord.js/src/util/Sweepers.js [hunk 2]
```diff
@@ -425,6 +425,9 @@ class Sweepers {
     let items = 0;
 
     for (const guild of this.client.guilds.cache.values()) {
+      // We may be unable to sweep the cache if the guild is unavailable and was never patched
```
Comment (vladfrangu) [inline packages/discord.js/src/util/Sweepers.js:428]: I'd rather skip sweeping entirely if guild.available is false instead of checking if a key is present, but others might disagree (so lets discuss it!)

Comment (didinele) [reply packages/discord.js/src/util/Sweepers.js:428]: I'm with Vlad here.

Comment (JMTK) [reply packages/discord.js/src/util/Sweepers.js:428]: Fixed!

File: packages/discord.js/src/util/Sweepers.js [hunk 3]
```diff
@@ -425,6 +425,9 @@ class Sweepers {
...
+      if (!guild.available) continue;
```
Comment (uhKevinMC) [inline packages/discord.js/src/util/Sweepers.js:429]:
```suggestion
      if (guild.available) continue;
```

Is the goal here to check if the guild is available before continuing? Right now it's checking if the guild is not available before continuing. I'm assuming you'd want the guild to be available if you want it to continue with sweeping

**Review by uhKevinMC — CHANGES_REQUESTED** [review]

File: packages/discord.js/src/util/Sweepers.js (hunk 3 above)
Comment (monbrey) [reply packages/discord.js/src/util/Sweepers.js:429]: I think you've misunderstood what `continue` does - it stops executing this item in the loop skips to the next item / iterable.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/continue

Comment (uhKevinMC) [reply packages/discord.js/src/util/Sweepers.js:429]: I stand corrected 👍🏻 

I'll go take a trip down Mozillas keywords list

**Review by didinele — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
