### PR TITLE
fix(MessageMentions): infinite loop in `parsedUsers` getter

### LINKED ISSUE #8426: Infinite loop on MessageMentions `parsedUsers` getter
### Which package is this bug report for?

discord.js

### Issue description

In the getter for the `MessageMentions#parsedUsers` when the `this._parsedUsers` is a falsy value what prevents this code from creating an infinite loop?

Since if the content has mentions the `this.constructor.UsersPattern.exec(this._content)` will always be truthy and `UsersPattern` isn't a global Regex so no `lastIndex`.

> **Warning**
> May cause memory leaks or stack overflow!

### Code sample

```typescript
/**
   * Any user mentions that were included in the message content
   * <info>Order as they appear first in the message content</info>
   * @type {Collection<Snowflake, User>}
   * @readonly
   */
  get parsedUsers() {
    if (this._parsedUsers) return this._parsedUsers;
    this._parsedUsers = new Collection();
    let matches;
    while ((matches = this.constructor.UsersPattern.exec(this._content)) !== null) {
      const user = this.client.users.cache.get(matches[1]);
      if (user) this._parsedUsers.set(user.id, user);
    }
    return this._parsedUsers;
  }

// https://github.com/discordjs/discord.js/blob/359f6885558fcfb3151971ab589077a89ee71a01/packages/discord.js/src/structures/MessageMentions.js#L224
```

### Package version

14.1.2

### Node.js version

Node v17.9.1 and Ts v4.7.4

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (internal bug)

### Which gateway intents are you subscribing to?

Not applicable (internal bug)

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #8426 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -1885,6 +1885,7 @@ export class MessageMentions {
   public static EveryonePattern: RegExp;
   public static RolesPattern: typeof FormattingPatterns.Role;
   public static UsersPattern: typeof FormattingPatterns.User;
+  private static GlobalUsersPattern: RegExp;
```
Comment (SpaceEEC) [inline packages/discord.js/typings/index.d.ts:1888]: Mind moving this (and the `GlobalChannelsPattern`) above the `ChannelsPattern`?

**Review by SpaceEEC — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
