### PR TITLE
types(Client): fix isReady narrowing

### LINKED ISSUE #9827: Client.isReady() improperly narrows type to never
### Which package is this bug report for?

discord.js

### Issue description

When `Client.isReady()` returns false, the type of Client in that scope is narrowed to `never`. That doesn't seem like it should be the case, as you should be able to do something like this:

```typescript
if (!client.isReady()) {
  // Error: Property 'once' does not exist on type 'never'.
  client.once(Events.ClientReady, () => {
        // do stuff
  })
}
```

As a workaround, you can look at `readyAt`, which will keep the type of Client as `Client<boolean>`:

```typescript
if (!client.readyAt) {
  client.once(Events.ClientReady, () => {
        // do stuff
  })
}
```

### Code sample

```typescript
import { Client, Events } from "discord.js"

const client = new Client(clientOptions)

if (!client.isReady()) {
  client.once(Events.ClientReady, () => {
    // do stuff
  })
}
```

### Versions

- discord.js 14.13.0
- typescript 5.2.2

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by N1ckPro**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #9827 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -955,6 +955,7 @@ export class Client<Ready extends boolean = boolean> extends BaseClient {
   private _eval(script: string): unknown;
   private _validateOptions(options: ClientOptions): void;
   private get _censoredToken(): string | null;
+  private readonly _ready: Ready;
```
Comment (Jiralite) [inline packages/discord.js/typings/index.d.ts:958]: A comment would be ideal as to why this is needed and not present in JavaScript like so:

https://github.com/discordjs/discord.js/blob/c50809e20648cacea99f5450e8073d960ff8aa39/packages/discord.js/typings/index.d.ts#L1799-L1800

**Review by Jiralite — COMMENTED** [review]
Will you add tests, please?

File: packages/discord.js/typings/index.test-d.ts [hunk 2]
```diff
@@ -197,6 +197,10 @@ const client: Client = new Client({
   }),
 });
 
+if (client.isReady()) {
```
Comment (didinele) [inline packages/discord.js/typings/index.test-d.ts:200]: Please also add one for the opposite case, since that was actually the problematic one.

**Review by didinele — CHANGES_REQUESTED** [review]

**Review by didinele — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by jaw0r3k — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
