### PR TITLE
fix: properly serialize `undefined` values

### LINKED ISSUE #7510: [dev] Transformers.toSnakeCase method converts undefined values into empty objects.
### Which package is this bug report for?

discord.js

### Issue description

The Transformers.toSnakeCase method converts undefined values into empty objects.

### Code sample

```typescript
import {Options} from 'discord.js';

console.dir(Options.createDefault().jsonTransformer({snakeCaseKey:undefined}))
```

### Package version

@dev

### Node.js version

node v17.2.0

### Operating system

arch linux

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageMentions, DirectMessageTyping, GuildScheduledEvents

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

This fixes an issue where if a value is explicitly set to `undefined`, it would be serialized as `{}`.

Closes #7510 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/util/Transformers.js [hunk 1]
```diff
@@ -12,7 +12,10 @@ class Transformers extends null {
     if (typeof obj !== 'object' || !obj) return obj;
     if (Array.isArray(obj)) return obj.map(Transformers.toSnakeCase);
     return Object.fromEntries(
-      Object.entries(obj).map(([key, value]) => [snakeCase(key), Transformers.toSnakeCase(value)]),
+      Object.entries(obj).map(([key, value]) => [
+        snakeCase(key),
+        typeof value === 'undefined' ? value : Transformers.toSnakeCase(value),
```
Comment (vladfrangu) [inline packages/discord.js/src/util/Transformers.js:17]: you should just remove the default of `obj = {}` instead

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
