### PR TITLE
typings(PartialUser): fix PartialUser remove `deleted` property

### LINKED ISSUE #4615: Partialize is adding 'deleted' on PartialUser
**Please describe the problem you are having in as much detail as possible:**
[Partialize](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2834) applies an invalid `deleted` property on PartialUser.

**Include a reproducible code sample here, if possible:**
```ts
async function handleReaction(reaction: MessageReaction, user: User | PartialUser): Promise<void> {}

function init() {
    /**
     * Argument of type 'import("discord.js").User | import("discord.js").PartialUser' is not assignable to parameter of type 'User | import("discord.js").PartialUser'.
     * Type 'User' is not assignable to type 'User | PartialUser'.
     * Property 'deleted' is missing in type 'User' but required in type 'PartialUser'.ts(2345)
     *	index.d.ts(2818, 5): 'deleted' is declared here.
     */
    this.client.on('messageReactionAdd', (r, u) => this.handleReaction(r, u));
}
```

**Further details:**

- TypeScript version: `3.9.6`
- discord.js version: `12.2.0_6654e116f35a749c9e625e33223ad548`
- Node.js version: `v14.4.0`
- Operating system: `Manjaro Linux`
- Priority this issue should have – please be realistic and elaborate if possible: minor, can just use ts-ignore for the time being

- [ ] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by wasdennnoch**
**Please describe the changes this PR makes and why it should be merged:**
Currently `Partialize` is adding the `deleted` property to all partial types using it, including `PartialUser`, which is wrong as a `User` can't have the `deleted` property.
Additionally, `Partialize` is already making all properties nullable, so explicitly setting `username` to null isn't required - even on a partial user it can be populated after e.g. a `USER_UPDATE` event.

Fixes #4615

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -3031,13 +3031,11 @@ declare module 'discord.js' {
...
   type PartialTypes = 'USER' | 'CHANNEL' | 'GUILD_MEMBER' | 'MESSAGE' | 'REACTION';
 
-  interface PartialUser extends Partialize<User, 'bot' | 'flags' | 'locale' | 'system' | 'tag' | 'username'> {
+  interface PartialUser extends Omit<Partialize<User, 'bot' | 'flags' | 'locale' | 'system'>, "deleted"> {
     bot: User['bot'];
     flags: User['flags'];
     locale: User['locale'];
     system: User['system'];
-    readonly tag: null;
-    username: null;
```
Comment (NotSugden) [inline typings/index.d.ts:3040]: no, if you look at the `partial` getter, https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/src/structures/User.js#L120 you can see the username has to not be a string for it to be partial, and the `tag` getter https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/src/structures/User.js#L200 it returns null if there is no username, and the `Partialize` type sets it to `string | null` https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/typings/index.d.ts#L2940

File: typings/index.d.ts [hunk 2]
```diff
@@ -3031,13 +3031,11 @@ declare module 'discord.js' {
 
   type PartialTypes = 'USER' | 'CHANNEL' | 'GUILD_MEMBER' | 'MESSAGE' | 'REACTION';
 
-  interface PartialUser extends Partialize<User, 'bot' | 'flags' | 'locale' | 'system' | 'tag' | 'username'> {
+  interface PartialUser extends Omit<Partialize<User, 'bot' | 'flags' | 'locale' | 'system'>, "deleted"> {
```
Comment (NotSugden) [inline typings/index.d.ts:3034]:
```suggestion
  interface PartialUser extends Partialize<User, 'bot' | 'flags' | 'locale' | 'system' | 'tag' | 'username' | 'deleted'> {
```
in-line with previous comment and not sure why you used Omit there, thats what the 2nd type param for `Partialize` is for

**Review by NotSugden — CHANGES_REQUESTED** [review]

File: typings/index.d.ts (hunk 2 above)
Comment (wasdennnoch) [reply typings/index.d.ts:3034]: The way I understand it is that the 2nd param only controls keys from the original type (`User`) and `Partialize` always adds its own properties on top without them being affected by the 2nd param in any way, no? So putting `deleted` there would only remove `deleted` from `User`, not `Partialize`.
The Base `Partialize` type is AND-ed with the rest here: https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/typings/index.d.ts#L2928-L2941

Comment (NotSugden) [reply typings/index.d.ts:3034]: oh right, facepalm there, mb

File: typings/index.d.ts (hunk 1 above)
Comment (wasdennnoch) [reply typings/index.d.ts]: Ah, didn't realize partial users could have more than just the ID set. Apparently `USER_UPDATE` always contains the full user, not partial updates. I've reverted that change.

File: typings/index.d.ts (hunk 2 above)
Comment (NotSugden) [reply typings/index.d.ts]: quotes should be single quotes too, not double quotes

Comment (wasdennnoch) [reply typings/index.d.ts]: Fixed

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
