### PR TITLE
fix: set #nickname to null as the default value

### LINKED ISSUE #4640: GuildMember.nickname has incorrect typings
**Please describe the problem you are having in as much detail as possible:**
I am trying to avoid saving a nickname if it is not set, but the typings incorrectly claim `string | null` when it is actually `string | undefined`.

**Include a reproducible code sample here, if possible:**

```js
    const nickname = member.nickname;
    if (nickname !== null) {
        console.log(memTag, 'Saving name:', nickname);
        setUserName(member.user.id, member.guild.id, nickname);
    }
```

This code will log "Saving name: undefined" when someone has no nickname, rather than not logging a message at all.

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 14.1.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: High priority, causes unexpected bugs due to undeclared branch possibilities that the compiler cannot know

- [x] I have also tested the issue on latest master, commit hash: f9f36610

### PR DESCRIPTION
**Pull request by PASTUSEDBY**
**Please describe the changes this PR makes and why it should be merged:**

* closes #4640

According to #4640, the `.nickname` property of a guildmember returns `undefined` instead of `null` if not present.
This might be due to the way the library currently handles and assigns the initial `data` payload received from Discord itself.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
     - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
 - [ ] This PR only includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/GuildMember.js [hunk 1]
```diff
@@ -66,17 +66,19 @@ class GuildMember extends Base {
...
      */
-    if (typeof data.nick !== 'undefined') this.nickname = data.nick;
+    this.nickname = null;
+
+    this._roles = [];
+    if (data) this._patch(data);
+  }
+
+  _patch(data) {
+    if (typeof data.nick === 'string') this.nickname = data.nick;
```
Comment (kyranet) [inline src/structures/GuildMember.js:81]: This has a problem.

If the GuildMember had a nickname set, and then removes it, this if branch won't be called and so it won't be set to null.

Please revert it to the previous condition, `typeof data.nick !== 'undefined'` is more accurate.

Comment (PASTUSEDBY) [reply src/structures/GuildMember.js:81]: Oh right, I literally forgot about when the member would edit their nickname, will fix it.
