### PR TITLE
types: Swap message reaction and emoji identifier types

### LINKED ISSUE #8968: Typing error for reactions
### Which package is this bug report for?

discord.js

### Issue description

In the #5717 PR were added some additional typings for MessageReactionResolvable.
image

There is actually no code that can parse it in the [`MessageReactionManager>.resolve()`](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/managers/DataManager.js#L34-L43) (there is no override of the `<DataManager>.resolve()`).
A string is not an instance of MessageReaction, and those formulations are not indexes of Collection cached reactions (id or name). 

### Package version

dev

### Priority this issue should have

Medium (should be fixed soon)

### I have tested this issue on a development release

22e2bbb0d24e3f30516f262308d5786f2f666713

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Resolves #8968 by somewhat swapping the types for `EmojiIdentifierResolvable` and `MessageReactionResolvable`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by DraftProducts — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -5040,7 +5040,12 @@ export interface EmbedField {
   inline: boolean;
 }
 
-export type EmojiIdentifierResolvable = string | EmojiResolvable;
+export type EmojiIdentifierResolvable =
+  | EmojiResolvable
+  | `${string}:${Snowflake}`
+  | `<:${string}:${Snowflake}>`
+  | `<a:${string}:${Snowflake}>`
```
Comment (kyranet) [inline packages/discord.js/typings/index.d.ts:5047]: You can simplify the two into a single one:
```suggestion
  | `<${'' | 'a'}:${string}:${Snowflake}>`
```

That being said, this is all union'd with `string`, so the string template types are... ignored.

File: packages/discord.js/typings/index.d.ts [hunk 2]
```diff
@@ -5040,7 +5040,12 @@ export interface EmbedField {
   inline: boolean;
 }
 
-export type EmojiIdentifierResolvable = string | EmojiResolvable;
+export type EmojiIdentifierResolvable =
+  | EmojiResolvable
+  | `${string}:${Snowflake}`
```
Comment (kyranet) [inline packages/discord.js/typings/index.d.ts:5045]: Seeing `a:name:id` is supported according to the jsdoc:
```suggestion
  | `${'' | 'a:'}${string}:${Snowflake}`
```

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]

**Review by DraftProducts — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
