### PR TITLE
types(CategoryChannelChildManager): fix Holds type

### LINKED ISSUE #8287: Incorrect type for CategoryChannelChildManager#cache
### Which package is this bug report for?

discord.js

### Issue description

The type for CategoryChannelChildManager#cache is wrong as it says it can include thread channels, which is not true. The type for Holds on the manager is currently NonCategoryGuildBasedChannel which simply removes CategoryChannel from GuildBasedChannel, it should instead remove thread channels too.

### Code sample

```typescript
const category = guild.channels.cache.get("ID_HERE") as CategoryChannel
for (const child of category.children.cache.values())
	child.setParent("PARENT_ID", { reason: "Moving this channel" }) // Error: Property 'setParent' does not exist on type 'NonCategoryGuildBasedChannel'. Property 'setParent' does not exist on type 'PublicThreadChannel'. ts(2339)
```

### Package version

14.0.0-dev.1657411900-f0b68d5

### Node.js version

18.5.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

f0b68d5

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #8287. If you have better suggestions for the type feel free to leave them here.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -5433,7 +5429,7 @@ export type VoiceBasedChannel = Extract<Channel, { bitrate: number }>;
 
 export type GuildBasedChannel = Extract<Channel, { guild: Guild }>;
 
-export type NonCategoryGuildBasedChannel = Exclude<GuildBasedChannel, CategoryChannel>;
+export type CategoryChildChannel = Exclude<Extract<Channel, { parent: CategoryChannel | null }>, CategoryChannel>;
```
Comment (vladfrangu) [inline packages/discord.js/typings/index.d.ts:5432]: Is the Exclude necessary?

Comment (ImRodry) [reply packages/discord.js/typings/index.d.ts:5432]: Yes otherwise the type would include CategoryChannel. The property is inherited from GuildChannel and even if you override it with null (which is the value it will always have) it would still show up, I tested that

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
