### PR TITLE
fix(Interaction): add missing types and fix docs lists

### LINKED ISSUE #5751: Interaction#componentType
**Please describe the problem you are having in as much detail as possible:** The guide says to check `if (!interaction.isMessageComponent() && interaction.componentType !== 'BUTTON') return;` while listening for buttons, however there are no typings for `Interaction#componentType`

**Include a reproducible code sample here, if possible:** image

```js
// Place your code here
```

**Further details:**

- discord.js version: Dev Branch cbd7f2b9aa44a9240947ed716d0e72257ac499f7 
- Node.js version: 14.0
- Operating system: Ubuntu 20
- Priority this issue should have – please be realistic and elaborate if possible: Medium, as it may be required to distinguish between buttons and (?)

**Relevant client options:**

- partials: All
- gateway intents: All
- other: none

 cbd7f2b9aa44a9240947ed716d0e72257ac499f7

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
This fixes #5751 as well as a bug in two typedefs that had their possible types listed incorrectly.
Decided to make this smaller PR to fix that issue as it can be quite annoying for users that are just now starting to try MessageComponents to have to wait for #5692 to be merged, as this will clearly take a while

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -1328,6 +1328,7 @@ declare module 'discord.js' {
   }
 
   export class MessageComponentInteraction extends Interaction {
+    public componentType: MessageComponentType | MessageComponentTypes;
```
Comment (SpaceEEC) [inline typings/index.d.ts:1331]: This should always be the string, not integer:
```suggestion
    public componentType: MessageComponentType;
```
See:
https://github.com/discordjs/discord.js/blob/69bb5f911091e433ad3241d02b5beaca6426d433/src/structures/MessageComponentInteraction.js#L33
https://github.com/discordjs/discord.js/blob/69bb5f911091e433ad3241d02b5beaca6426d433/src/structures/MessageComponentInteraction.js#L60-L62

**Review by SpaceEEC — CHANGES_REQUESTED** [review]

File: typings/index.d.ts (hunk 1 above)
Comment (ImRodry) [reply typings/index.d.ts:1331]: Ah I saw that but forgot to change it, my bad!

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
