### PR TITLE
fix(Client): Ensure destroyed connections are not ready

### LINKED ISSUE #9941: Calling client.destroy() doesn't make client.isReady() return false
### Which package is this bug report for?

discord.js

### Issue description

1. Log in with a Client with the `login()` function.
2. Then call the `destroy()` function to this same client.
3. And check that the `isReady()` function still returns `true` even though the `client.ws.destroyed` property is `true`.

### Code sample

```typescript
const { Client, GatewayIntentBits } = require('discord.js');

const client = new Client({
	intents: [
		GatewayIntentBits.Guilds,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.MessageContent,
		GatewayIntentBits.GuildMessageReactions,
	],
});

const main = async () => {
	await client.login();
	console.log(client.isReady());
	console.log(client.ws.destroyed);
	await client.destroy();
	console.log(client.isReady());
	console.log(client.ws.destroyed);
};

main();
```

### Versions

- discord.js@14.13.0
- node v20.9.0
- Linux cursed 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, GuildMessageReactions, MessageContent

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Resolves #9941.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/client/Client.js [hunk 1]
```diff
@@ -239,7 +239,7 @@ class Client extends BaseClient {
    * @returns {boolean}
    */
   isReady() {
-    return this.ws.status === Status.Ready;
+    return this.ws.destroyed === false && this.ws.status === Status.Ready;
```
Comment (kyranet) [inline packages/discord.js/src/client/Client.js:242]: I don't think we do `=== false` unless there's also another value with a different meaning. Negating the value should be fine:
```suggestion
    return !this.ws.destroyed && this.ws.status === Status.Ready;
```

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
Might be nicer to have a `Destroyed` state on the WS, but well
