### PR TITLE
fix(*RoleManager): Create set of role ids correctly

### LINKED ISSUE #6673: Bug: API Error when trying to add an array of roles to a member if roles arent removed prior
### Issue description

1. Create two roles
2. Add yourself those two roles
3. Use the code sample below
4. Get a duplicate value error

Currently to counter this, you must remove the roles who are gonna be added first and then add the roles. This is really inconvenient.

### Codesample

```typescript
client.guilds.cache
      .get("guildId")
      .members.fetch("yourId")
      .then((m) =>
        m.roles.add([role1Id, role2Id])
      );
```

### discord.js version

13.1.0

### Node.js version

v16.9.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
The `Set` in these two managers were being created improperly as it compared ids with `Role`s, which wouldn't work. This pull request resolves this (and resolves #6673).

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/managers/GuildEmojiRoleManager.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ class GuildEmojiRoleManager extends DataManager {
       resolvedRoles.push(resolvedRole);
     }
 
-    const newRoles = [...new Set(resolvedRoles.concat(...this.cache.values()))];
+    const newRoles = [...new Set(resolvedRoles.concat(...this.cache.map(role => role.id)))];
```
Comment (vaporox) [inline src/managers/GuildEmojiRoleManager.js:54]:
```suggestion
    const newRoles = [...new Set(resolvedRoles.concat(...this.cache.keys()))];
```
I believe this should work too

File: src/managers/GuildMemberRoleManager.js [hunk 2]
```diff
@@ -102,7 +102,7 @@ class GuildMemberRoleManager extends DataManager {
         resolvedRoles.push(resolvedRole);
       }
 
-      const newRoles = [...new Set(resolvedRoles.concat(...this.cache.values()))];
+      const newRoles = [...new Set(resolvedRoles.concat(...this.cache.map(role => role.id)))];
```
Comment (vaporox) [inline src/managers/GuildMemberRoleManager.js:105]:
```suggestion
      const newRoles = [...new Set(resolvedRoles.concat(...this.cache.keys()))];
```

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
