### PR TITLE
fix(GuildChannel): setParent not working

### LINKED ISSUE #6275: channel.setParent not doing anything and returns no errors
I've spent about 5 hours updating my code to work with v13 from v12 and I got to a point where I physically can't move any further.
I've spent at least 2 hours trying to get it to work and I'm just getting no where, `channel.setParent()` is doing absolutely nothing, no error and the channel doesn't move into a diff category.

```
client.on('messageCreate', async message => {    
        if (message.content.toLowerCase() === '!test') {
            var guild = client.guilds.cache.get('847246917654151168')
            var channel = guild.channels.cache.get('871801544004235356')
            var log = await channel.setParent('847246918220251160', { lockPermissions: false })
            console.log(log)
        }
    })
```

**Further details:**

- discord.js version: 13.0.0-dev.t1627906063.6e0ea02
- Node.js version: v14.17.4
- Operating system: Windows 11 - 10.0.22000 Build 22000
- Priority this issue should have – please be realistic and elaborate if possible: It's high for me but I wouldn't know about everyone else, anyone with a ticket system that changes the parent wouldn't function.

**Relevant client options:**

- partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'USER', 'GUILD_MEMBER']
- gateway intents: ALL
- other: none

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
This fixes an issue introduced by #6210 that made setParent not work at all. Fixes #6275 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/structures/GuildChannel.js [hunk 1]
```diff
@@ -388,7 +388,7 @@ class GuildChannel extends Channel {
   setParent(channel, { lockPermissions = true, reason } = {}) {
     return this.edit(
       {
-        parentId: channel?.id ?? channel ?? null,
+        parent: channel?.id ?? channel ?? null,
```
Comment (NotSugden) [inline src/structures/GuildChannel.js:391]:
```suggestion
        parent: channel ?? null,
```
i suppose this can also be changed (as that was originally what was on the PR)

**Review by ItsKodas — APPROVED** [review]

File: src/structures/GuildChannel.js (hunk 1 above)
Comment (ImRodry) [reply src/structures/GuildChannel.js:391]: Yeah I guess since we're resolving the id anyway in .edit might as well keep that.

Comment (Jiralite) [reply src/structures/GuildChannel.js:391]: Yes please. This check is already in the edit, so it would be duplicating the check.

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by ItsKodas** [comment]
Thanks for the hotfix :)
