### PR TITLE
fix(Emoji): remove incorrect nullables, add `ApplicationEmoji#available`

### LINKED ISSUE #10858: Incorrect typing for `ApplicationEmoji`
### Which package is this bug report for?

discord.js

### Issue description

The property `ApplicationEmoji#name` is never null since that is only possible for reaction emojis
The property `ApplicationEmoji#animated` is never null since that is only possible for unicode reaction emojis

The property `ApplicationEmoji#author` cannot be null ddocs state that:
> Includes a user object for the team member that uploaded the emoji from the app's settings, or for the bot user if uploaded using the API.

I'm not really sure whether this information is correct but from my point of view, these properties, and maybe some more could never be null. If I'm wrong please correct me.

### Code sample

```typescript

```

### Versions

- discord.js@14.19.1
- typescript@5.8.3

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Amgelo563**
**Please describe the changes this PR makes and why it should be merged:**

ApplicationEmoji and BaseGuildEmoji inherit some incorrect nullables from Emoji (since they are never null for their case). Also BaseGuildEmoji#url wasn't marked as deprecated in the index.d.ts and ApplicationEmoji#available was missing (though always true, added for consistency with the rest). Internal discussion at https://discord.com/channels/222078108977594368/1366526457064591440/1366526457064591440

Supersedes #10905
Supersedes #10912

Fixes #10858 

### Typings
- Remove `| null` from `ApplicationEmoji#author`, `managed`, and `requiresColons`
- Change `ApplicationEmoji#managed`'s type to `false` and `requiresColons` to `true`
- Add `ApplicationEmoji#available: true`
- Type override `ApplicationEmoji#name`, `animated`, `imageURL`, `createdAt` and `createdTimestamp` to make them non nullable
- Type override `BaseGuildEmoji#name`, `animated`, and `managed` to make them non nullable (the other properties were already non nullable)
- Remove `BaseGuildEmoji#url` and `Emoji#url` since those aren't present in runtime anymore
### JS
- Add jsdoc comments overriding `ApplicationEmoji#name`, `animated`, `imageURL`, `createdAt` and `createdTimestamp`'s to remove the "or null if unicode" mentions
- Add jsdoc comments overriding `BaseGuildEmoji#name`, `animated`, `createdAt` and `createdTimestamp`'s to remove the "or null if unicode" mentions (`imageURL` already has them)
- Add `available` on `ApplicationEmoji`:
  - Set to `null` in constructor
  - Set in `_patch()`
  - Add check to `equals()`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -590,14 +590,17 @@ export abstract class BaseGuild extends Base {
 
 export class BaseGuildEmoji extends Emoji {
   protected constructor(client: Client<true>, data: APIEmoji, guild: Guild | GuildPreview);
-  public imageURL(options?: ImageURLOptions): string;
+  public imageURL(options?: BaseImageURLOptions): string;
```
Comment (Qjuh) [inline packages/discord.js/typings/index.d.ts:593]:
```suggestion
  public imageURL(options?: ImageURLOptions): string;
```

File: packages/discord.js/typings/index.d.ts [hunk 2]
```diff
@@ -1286,10 +1289,18 @@ export class ApplicationEmoji extends Emoji {
...
+  public managed: false;
+  public requiresColons: true;
+  public name: string;
+  public animated: boolean;
+  public available: true;
+  public get createdAt(): Date;
+  public get createdTimestamp(): number;
+  /** @deprecated Use {@link ApplicationEmoji.imageURL} instead */
+  public get url(): string;
+  public imageURL(options?: BaseImageURLOptions): string;
```
Comment (Qjuh) [inline packages/discord.js/typings/index.d.ts:1303]:
```suggestion
  public imageURL(options?: ImageURLOptions): string;
```

File: packages/discord.js/src/structures/ApplicationEmoji.js [hunk 3]
```diff
@@ -107,12 +112,68 @@ class ApplicationEmoji extends Emoji {
...
+ * @type {boolean}
+ * @readonly
+ */
+
+/**
+ * Returns a URL for the emoji.
+ * @method imageURL
+ * @memberof ApplicationEmoji
+ * @instance
+ * @param {BaseImageURLOptions} [options] Options for the image URL
```
Comment (Qjuh) [inline packages/discord.js/src/structures/ApplicationEmoji.js:147]:
```suggestion
 * @param {ImageURLOptions} [options] Options for the image URL
```

**Review by Qjuh — CHANGES_REQUESTED** [review]

**Review by Qjuh — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 4]
```diff
@@ -1286,10 +1289,18 @@ export class ApplicationEmoji extends Emoji {
...
-  public requiresColons: boolean | null;
+  public managed: false;
+  public requiresColons: true;
+  public name: string;
+  public animated: boolean;
+  public available: true;
+  public get createdAt(): Date;
+  public get createdTimestamp(): number;
+  /** @deprecated Use {@link ApplicationEmoji.imageURL} instead */
+  public get url(): string;
```
Comment (Jiralite) [inline packages/discord.js/typings/index.d.ts:1302]: This does not exist.

```suggestion
```

File: packages/discord.js/src/structures/BaseGuildEmoji.js [hunk 5]
```diff
@@ -62,4 +62,50 @@ class BaseGuildEmoji extends Emoji {
...
+/**
+ * Returns a URL for the emoji.
+ * @name url
+ * @memberof BaseGuildEmoji
+ * @instance
+ * @type {string}
+ * @readonly
+ * @deprecated Use {@link BaseGuildEmoji#imageURL} instead.
+ */
+
```
Comment (Jiralite) [inline packages/discord.js/src/structures/BaseGuildEmoji.js:74]:
```suggestion
```

File: packages/discord.js/src/structures/ApplicationEmoji.js [hunk 6]
```diff
@@ -16,37 +16,42 @@ class ApplicationEmoji extends Emoji {
...
+       * @type {User}
+       */
+      this.author = this.client.users._add(data.user);
+    }
 
     if ('managed' in data) {
       /**
-       * Whether this emoji is managed by an external service
-       * @type {?boolean}
+       * Whether this emoji is managed by an external service. Always false for application emojis
```
Comment (Jiralite) [inline packages/discord.js/src/structures/ApplicationEmoji.js:34]:
```suggestion
       * Whether this emoji is managed by an external service. Always `false` for application emojis
```

File: packages/discord.js/src/structures/ApplicationEmoji.js [hunk 7]
```diff
@@ -16,37 +16,42 @@ class ApplicationEmoji extends Emoji {
...
+       * @type {false}
        */
       this.managed = data.managed;
     }
 
     if ('require_colons' in data) {
       /**
-       * Whether or not this emoji requires colons surrounding it
-       * @type {?boolean}
+       * Whether or not this emoji requires colons surrounding it. Always true for application emojis
```
Comment (Jiralite) [inline packages/discord.js/src/structures/ApplicationEmoji.js:42]:
```suggestion
       * Whether this emoji requires colons surrounding it. Always `true` for application emojis
```

**Review by Jiralite — CHANGES_REQUESTED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
