### PR TITLE
fix: allowedMentions, container, media item `toJSON()` for components v2

### LINKED ISSUE #10855: Wrong typing for MessageEditOptions#flags
### Which package is this bug report for?

discord.js

### Issue description

With the release of the new ComponentsV2, deferring a reply does not allow the flag MessageFlags.IsComponentV2, but editReply typing does not allow it too!
The type https://github.com/discordjs/discord.js/blob/14.19.1/packages/discord.js/typings/index.d.ts#L7046 seems to be wrong and should include IsComponentsV2.

### Code sample

```typescript
client.on("interactionCreate", async interaction => {
  if(interaction.isChatInputCommand()) {
    await interaction.deferReply()
    await interaction.editReply({
      components: [
        new ContainerBuilder()
          .addTextDisplayComponents(new TextDisplayBuilder().setContent("hi!"))
      ],
      flags: MessageFlags.IsComponentsV2
    })
  }
})
```

### Versions

- discord.js v14.19.1
- node v22.15.0
- typescript v5.8.3
- win11

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Qjuh**
**Please describe the changes this PR makes and why it should be merged:**

Fixes an issue where allowedMentions don't get used in MessagePayload if `IsComponentsV2`.

Fixes #10855

Adds the missing `UnfurledMediaItem#toJSON()`.

Fixes `MessageComponentInteraction#component` not working for components in an ActionRow inside a Container.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/structures/MessagePayload.js [hunk 1]
```diff
@@ -248,7 +248,13 @@ class MessagePayload {
       components,
       username,
       avatar_url: avatarURL,
-      allowed_mentions: content === undefined && message_reference === undefined ? undefined : allowedMentions,
+      allowed_mentions:
+        content === undefined &&
+        message_reference === undefined &&
+        // Components V2 can mention, so need to check for them too
+        (!components?.length || flags & (MessageFlags.IsComponentsV2 === 0))
```
Comment (almeidx) [inline packages/discord.js/src/structures/MessagePayload.js:255]:
```suggestion
        (!components?.length || (flags & MessageFlags.IsComponentsV2) === 0)
```

Comment (Qjuh) [reply packages/discord.js/src/structures/MessagePayload.js:255]: Did a complete refactor instead, as the original intention of this was to prevent passing allowedMentions if editing another user's message's flags.

File: packages/discord.js/src/structures/MessagePayload.js [hunk 2]
```diff
@@ -248,7 +248,8 @@ class MessagePayload {
       components,
       username,
       avatar_url: avatarURL,
-      allowed_mentions: content === undefined && message_reference === undefined ? undefined : allowedMentions,
+      allowed_mentions:
+        this.isMessage() && this.target.author.id !== this.target.client.user.id ? undefined : allowedMentions,
```
Comment (Jiralite) [inline packages/discord.js/src/structures/MessagePayload.js:252]: This is not a function.

**Review by Jiralite — CHANGES_REQUESTED** [review]

File: packages/discord.js/src/structures/MessagePayload.js (hunk 2 above)
Comment (Qjuh) [reply packages/discord.js/src/structures/MessagePayload.js:252]:
```suggestion
        this.isMessage && this.target.author.id !== this.target.client.user.id ? undefined : allowedMentions,
```

**Review by vladfrangu — APPROVED** [review]

**Comment by vladfrangu** [comment]
Forward-port this please

**Review by didinele — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]
