### PR TITLE
fix(handlers): create burst handler for interaction callbacks

### LINKED ISSUE #9019: Request route for interaction responses includes the token
### Which package is this bug report for?

rest

### Issue description

The request route for an interaction reply of any kind includes the token, which makes it impossible to compare the route against a fixed string like we can do for others (which I believe is the point of having this route and not just the path). It would be nice to see the token be replaced with something like `:token` like is done for the id
image

### Code sample

```typescript
client.rest.on("response", req => console.log(req.route))
```

### Package version

1.4.0

### Node.js version

18.12.1

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by ckohen**
**Please describe the changes this PR makes and why it should be merged:**

Interaction callbacks currently create a queue per callback, this is unnecessary and consumes excess memory for no reason.
The burst handler ignores all ratelimits (except for hitting 429s) because that's what callbacks do. 

What do we think of how the route is handled with this? As it currently is this resolves #9019 

_Also solves the testing issue on Node 18+_

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+import { RESTEvents } from '../utils/constants.js';
+import { onRateLimit, parseHeader, parseResponse, shouldRetry } from '../utils/utils.js';
+import type { IHandler, PolyFillAbortSignal } from './IHandler.js';
+
+/**
+ * The structure used to handle burst requests for a given bucket.
+ * Burst requests have no ratelimit handling but allow for pre- and post-processing
+ * of data in the same manner as sequentially queued requests.
+ *
+ * <info>This queue may still emit a rate limit error if an unexpected 429 is hit</info>
```
Comment (almeidx) [inline packages/rest/src/lib/handlers/BurstHandler.ts:17]: Shouldn't this use a `@remark` instead of an info tag?

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+					`  Sublimit       : None`,
+				].join('\n'),
+			);
+
+			// We are bypassing all other limits, but an encountered limit should be respected (it's probably a non-punished ratelimit anyways)
+			await sleep(retryAfter);
+
+			// Since this is not a server side issue, the next request should pass, so we don't bump the retries counter
+			return this.runRequest(routeId, url, options, requestData, retries);
+		} else if (status >= 500 && status < 600) {
```
Comment (vladfrangu) [inline packages/rest/src/lib/handlers/BurstHandler.ts:158]: While this is good to have, this is useless for interactions as if it times out, we're most likely past the 3s limit too. Leaving it up to you if we should keep this

Comment (ckohen) [reply packages/rest/src/lib/handlers/BurstHandler.ts:158]: I left this in for the case where interaction callbacks aren't the only thing using this handler. That may never happen but if it does we let discord error which I think is better?

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+import { onRateLimit, parseHeader, parseResponse, shouldRetry } from '../utils/utils.js';
+import type { IHandler, PolyFillAbortSignal } from './IHandler.js';
+
+/**
+ * The structure used to handle burst requests for a given bucket.
+ * Burst requests have no ratelimit handling but allow for pre- and post-processing
+ * of data in the same manner as sequentially queued requests.
+ *
+ * @remarks
+ * This queue may still emit a rate limit error if an unexpected 429 is hit</info>
```
Comment (Jiralite) [inline packages/rest/src/lib/handlers/BurstHandler.ts:18]:
```suggestion
 * This queue may still emit a rate limit error if an unexpected 429 is hit
```

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+		url: string,
+		options: Omit<Dispatcher.RequestOptions, 'method' | 'origin' | 'path'> &
+			Partial<Pick<Dispatcher.RequestOptions, 'method'>> & { dispatcher?: Dispatcher },
+		requestData: HandlerRequestData,
+	): Promise<Dispatcher.ResponseData> {
+		return this.runRequest(routeId, url, options, requestData);
+	}
+
+	/**
+	 * The method that actually makes the request to the api, and updates info about the bucket accordingly
```
Comment (Jiralite) [inline packages/rest/src/lib/handlers/BurstHandler.ts:67]:
```suggestion
	 * The method that actually makes the request to the API and updates info about the bucket accordingly
```

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+	 *
+	 * @param routeId - The generalized api route with literal ids for major parameters
+	 * @param url - The fully resolved url to make the request to
```
Comment (Jiralite) [inline packages/rest/src/lib/handlers/BurstHandler.ts:70]:
```suggestion
	 * @param url - The fully resolved URL to make the request to
```

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 6]
```diff
@@ -0,0 +1,185 @@
...
+			Partial<Pick<Dispatcher.RequestOptions, 'method'>> & { dispatcher?: Dispatcher },
+		requestData: HandlerRequestData,
+	): Promise<Dispatcher.ResponseData> {
+		return this.runRequest(routeId, url, options, requestData);
+	}
+
+	/**
+	 * The method that actually makes the request to the api, and updates info about the bucket accordingly
+	 *
+	 * @param routeId - The generalized api route with literal ids for major parameters
```
Comment (Jiralite) [inline packages/rest/src/lib/handlers/BurstHandler.ts:69]:
```suggestion
	 * @param routeId - The generalized API route with literal ids for major parameters
```

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 7]
```diff
@@ -0,0 +1,185 @@
...
+					`  Bucket         : ${routeId.bucketRoute}`,
+					`  Major parameter: ${routeId.majorParameter}`,
+					`  Hash           : ${this.hash}`,
+					`  Limit          : ${Number.POSITIVE_INFINITY}`,
+					`  Retry After    : ${retryAfter}ms`,
+					`  Sublimit       : None`,
+				].join('\n'),
+			);
+
+			// We are bypassing all other limits, but an encountered limit should be respected (it's probably a non-punished ratelimit anyways)
```
Comment (Jiralite) [inline packages/rest/src/lib/handlers/BurstHandler.ts:154]:
```suggestion
			// We are bypassing all other limits, but an encountered limit should be respected (it's probably a non-punished rate limit anyways)
```

**Review by didinele — APPROVED** [review]

File: packages/rest/src/lib/handlers/BurstHandler.ts [hunk 8]
```diff
@@ -0,0 +1,147 @@
...
+	}
+
+	/**
+	 * {@inheritDoc IHandler.queueRequest}
+	 */
+	public async queueRequest(
+		routeId: RouteData,
+		url: string,
+		options: Omit<Dispatcher.RequestOptions, 'method' | 'origin' | 'path'> &
+			Partial<Pick<Dispatcher.RequestOptions, 'method'>> & { dispatcher?: Dispatcher },
```
Comment (vladfrangu) [inline packages/rest/src/lib/handlers/BurstHandler.ts:58]:
```suggestion
		options: RequestOptions,
```

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
