### PR TITLE
fix(Message): throw error on missing channel

### LINKED ISSUE #6578: bug: editing a message without a cached channel throws a cryptic error
### Issue description

../node_modules/discord.js/src/structures/Message.js:627
    return this.channel.messages.edit(this, options);

I had a Message.edit() method inside awaitReactions, but when kicking the bot out of the server got this error, i was thinking it happened because when kicking the bot, the channel is not in his cache anymore, so i went to the line 627 in the Message.js structure and added onle line to the code.

I tested it a couple of times both ways, and the second one with the `if(!this.channel) return` line is working smoothly.
Hope it helps anyone with the same problem!

### Codesample

```typescript
// Original Message.js structure in Discord.js
edit(options) {
  return this.channel.messages.edit(this, options);
}

// Message.js structure edited
edit(options) {
  if(!this.channel) return;
  return this.channel.messages.edit(this, options);
}
```

### discord.js version

13.0.1

### Node.js version

16.6.1

### Operating system

Windows 10 x64

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
This PR makes it so all Message methods/getters that depend on the message's channel either throw an error when the channel is missing (for methods) or account for the possibility of the channel being null (getters). This is due to the fact that Message#channel became a getter in v13 iirc and this can result in the channel being missing if the client loses access to the channel by either being kicked from the guild or the channel being deleted. Fixes #6578 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -596,13 +596,13 @@ class Message extends Base {
    */
   get crosspostable() {
     return (
-      this.channel.type === 'GUILD_NEWS' &&
+      this.channel?.type === 'GUILD_NEWS' &&
       !this.flags.has(MessageFlags.FLAGS.CROSSPOSTED) &&
       this.type === 'DEFAULT' &&
-      this.channel.viewable &&
-      this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.SEND_MESSAGES) &&
+      this.channel?.viewable &&
```
Comment (NotSugden) [inline src/structures/Message.js:602]: there isno need to use optional chaining here, above `this.channel?.type === '...' && ...` would ensure channel exists

*unrelated but since `this.channel` is a getter now should it be declared as a variable first instead of repeated references*
```js
const { channel } = this;
return ...
```

**Review by NotSugden — CHANGES_REQUESTED** [review]
the errors here need to be returned with `Promise.reject(...);` not `throw`!

*on the non-async functions\**

File: src/structures/Message.js (hunk 1 above)
Comment (ImRodry) [reply src/structures/Message.js:602]: I forgot that it would stop after one of the conditions returns false, will revert that part then

Comment (ImRodry) [reply src/structures/Message.js]: As for the const channel, is it really needed? I mean these are just boolean checks so they should all be running at the same time. Also not sure if it's within the scope of this PR but you/the maintainers could tell me

**Comment by ImRodry** [comment]
> the errors here need to be returned with `Promise.reject(...);` not `throw`!
> 
> _on the non-async functions*_

I totally missed this, sorry, but what difference does it make? Can't the error still be caught with .catch?

**Comment by NotSugden** [comment]
>  Can't the error still be caught with .catch?
no

File: src/structures/Message.js (hunk 1 above)
Comment (NotSugden) [reply src/structures/Message.js]: yeah it is unrelated to this pr, just thought id mention it

since `this.channel` is a getter im assuming that the getter function is ran every time its referenced

so its essentially like

`this.client.channels.resolve(...)?.type === ... && this.client.channels.resolve(...)... && ...
```
or maybe im overthinking it and this isn't an issue, idk

File: src/structures/Message.js [hunk 2]
```diff
@@ -631,6 +631,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   edit(options) {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (DTrombett) [inline src/structures/Message.js:634]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```

File: src/structures/Message.js [hunk 3]
```diff
@@ -646,6 +647,7 @@ class Message extends Base {
    * }
    */
   crosspost() {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (DTrombett) [inline src/structures/Message.js:650]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```

File: src/structures/Message.js [hunk 4]
```diff
@@ -735,6 +741,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   reply(options) {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (DTrombett) [inline src/structures/Message.js:744]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```

File: src/structures/Message.js [hunk 5]
```diff
@@ -766,6 +773,7 @@ class Message extends Base {
    * @returns {Promise<ThreadChannel>}
    */
   startThread(options = {}) {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (DTrombett) [inline src/structures/Message.js:776]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```

File: src/structures/Message.js [hunk 6]
```diff
@@ -779,6 +787,7 @@ class Message extends Base {
    * @returns {Promise<Message>}
    */
   fetch(force = true) {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (DTrombett) [inline src/structures/Message.js:790]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```

**Review by DTrombett — COMMENTED** [review]
Non async functions will throw an error not catchable with the `.catch` method since there's no promise.

**Review by vladfrangu — DISMISSED** [review]
Other than all the suggested changes (non-async functions need to either be marked as async or `return Promise.reject(new Error)` for the errors to be .catch-able,; `const { channel } = this;` for all the getters (since otherwise it's exactly what @NotSugden said here https://github.com/discordjs/discord.js/pull/6581#discussion_r701607035)), LGTM

**Comment by ImRodry** [comment]
@vladfrangu only crosspostable used references to this.channel more than once so I only added it there, let me know if others need this as well

File: src/structures/Message.js [hunk 7]
```diff
@@ -560,7 +560,7 @@ class Message extends Base {
     return Boolean(
       !this.deleted &&
         (this.author.id === this.client.user.id ||
-          this.channel.permissionsFor?.(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
+          this.channel?.permissionsFor?.(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
```
Comment (GoldenAngel2) [inline src/structures/Message.js:563]:
```suggestion
          this.channel?.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
```
consistency, so it matches the rest (or change the other ones to match this one)

Comment (ImRodry) [reply src/structures/Message.js:563]: I did notice that optional chaining didn't make much sense but I decided to leave it alone since it's not quite within the scope of the PR is it
In reality that will never not be a function I think so we can leave it like that

Comment (NotSugden) [reply src/structures/Message.js:563]: actually DMChannels don't have the `permissionsFor` method

Comment (ImRodry) [reply src/structures/Message.js:563]: Ohhh right, should I add this to the other methods then?

Comment (NotSugden) [reply src/structures/Message.js:563]: well the other getters already ensure its a guild channel so shouldn't be needed for them

Comment (ImRodry) [reply src/structures/Message.js:563]: Marking this as resolved then

File: src/structures/Message.js [hunk 8]
```diff
@@ -572,7 +572,7 @@ class Message extends Base {
   get pinnable() {
     return (
       this.type === 'DEFAULT' &&
-      (!this.guild || this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false))
+      (!this.guild || this.channel?.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES, false))
     );
   }
```
Comment (almeidx) [inline src/structures/Message.js:577]: Change the return type to `?boolean` or cast the return to boolean

Comment (ImRodry) [reply src/structures/Message.js:577]: This still returns a boolean

Comment (almeidx) [reply src/structures/Message.js:577]: I never said it didn't, it also returns `undefined` right now though.

Comment (ImRodry) [reply src/structures/Message.js:577]: No it doesn’t because `boolean && undefined` returns false

**Review by Jiralite — CHANGES_REQUESTED** [review]
It's possible for this error to appear in direct messages:

```JavaScript
const client = new (require("discord.js").Client)({
  partials: [
    "CHANNEL",
    "MESSAGE",
  ],
  intents: [
    "DIRECT_MESSAGES"
  ]
});

client.on("channelDelete", (channel) => {
  channel.messages.cache.first().edit("hii");
});

client.on("ready", async () => {
  const message = await (await client.users.fetch("id")).send("hi");
  message.channel.delete();
});

client.login("token");
```

<details>
<summary>Response</summary>

```
/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/structures/Message.js:635
    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
                                             ^

Error [NO_GUILD_CHANNEL]: Could not find the channel where this message came from! It may have been deleted.
    at Message.edit (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/structures/Message.js:635:46)
    at Client.<anonymous> (/Users/jiralite/Documents/GitHub/Soulobby/source/test.js:37:34)
    at Client.emit (node:events:394:28)
    at ChannelDeleteAction.handle (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/client/actions/ChannelDelete.js:30:14)
    at Object.module.exports [as CHANNEL_DELETE] (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/client/websocket/handlers/CHANNEL_DELETE.js:4:32)
    at WebSocketManager.handlePacket (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/Users/jiralite/Documents/GitHub/Soulobby/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28) {
  [Symbol(code)]: 'NO_GUILD_CHANNEL'
}
```

</details>

In this case, the error message is actually wrong! I suggest removing the "guild" portion of the error as it can happen without guilds, in this case.

File: src/errors/Messages.js [hunk 9]
```diff
@@ -92,6 +92,7 @@ const Messages = {
   GUILD_OWNED: 'Guild is owned by the client.',
   GUILD_MEMBERS_TIMEOUT: "Members didn't arrive in time.",
   GUILD_UNCACHED_ME: 'The client user as a member of this guild is uncached.',
+  NO_GUILD_CHANNEL: 'Could not find the channel where this message came from! It may have been deleted.',
```
Comment (ImRodry) [inline src/errors/Messages.js:95]:
```suggestion
  CHANNEL_NOT_CACHED: 'Could not find the channel where this message came from in the cache!',
```

File: src/structures/Message.js [hunk 10]
```diff
@@ -631,6 +632,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   edit(options) {
+    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```
Comment (ImRodry) [inline src/structures/Message.js:635]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('CHANNEL_NOT_CACHED'));
```

File: src/structures/Message.js [hunk 11]
```diff
@@ -646,6 +648,7 @@ class Message extends Base {
    * }
    */
   crosspost() {
+    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```
Comment (ImRodry) [inline src/structures/Message.js:651]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('CHANNEL_NOT_CACHED'));
```

File: src/structures/Message.js [hunk 12]
```diff
@@ -659,6 +662,7 @@ class Message extends Base {
    *   .catch(console.error)
    */
   async pin() {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (ImRodry) [inline src/structures/Message.js:665]:
```suggestion
    if (!this.channel) throw new Error('CHANNEL_NOT_CACHED');
```

File: src/structures/Message.js [hunk 13]
```diff
@@ -673,6 +677,7 @@ class Message extends Base {
    *   .catch(console.error)
    */
   async unpin() {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (ImRodry) [inline src/structures/Message.js:680]:
```suggestion
    if (!this.channel) throw new Error('CHANNEL_NOT_CACHED');
```

File: src/structures/Message.js [hunk 14]
```diff
@@ -693,6 +698,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   async react(emoji) {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (ImRodry) [inline src/structures/Message.js:701]:
```suggestion
    if (!this.channel) throw new Error('CHANNEL_NOT_CACHED');
```

File: src/structures/Message.js [hunk 15]
```diff
@@ -713,6 +719,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   async delete() {
+    if (!this.channel) throw new Error('NO_GUILD_CHANNEL');
```
Comment (ImRodry) [inline src/structures/Message.js:722]:
```suggestion
    if (!this.channel) throw new Error('CHANNEL_NOT_CACHED');
```

File: src/structures/Message.js [hunk 16]
```diff
@@ -735,6 +742,7 @@ class Message extends Base {
    *   .catch(console.error);
    */
   reply(options) {
+    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```
Comment (ImRodry) [inline src/structures/Message.js:745]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('CHANNEL_NOT_CACHED'));
```

File: src/structures/Message.js [hunk 17]
```diff
@@ -766,6 +774,7 @@ class Message extends Base {
    * @returns {Promise<ThreadChannel>}
    */
   startThread(options = {}) {
+    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```
Comment (ImRodry) [inline src/structures/Message.js:777]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('CHANNEL_NOT_CACHED'));
```

File: src/structures/Message.js [hunk 18]
```diff
@@ -779,6 +788,7 @@ class Message extends Base {
    * @returns {Promise<Message>}
    */
   fetch(force = true) {
+    if (!this.channel) return Promise.reject(new Error('NO_GUILD_CHANNEL'));
```
Comment (ImRodry) [inline src/structures/Message.js:791]:
```suggestion
    if (!this.channel) return Promise.reject(new Error('CHANNEL_NOT_CACHED'));
```

**Review by ImRodry — COMMENTED** [review]
Reviewing cause I’m not home and this makes it easier to commit but @Jiralite is this good?

**Comment by Jiralite** [comment]
Those changes look good to me!

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
