### PR TITLE
fix(MessageEmbed): Skip validation of field when inside a message

### LINKED ISSUE #3892: Discord sending embeds with no name, causing lib exception
**Please describe the problem you are having in as much detail as possible:**

Running a bot that is not sending any embeds every. Seeing `RangeError [EMBED_FIELD_NAME]: MessageEmbed field names may not be empty.` being thrown by the library, completely internally based on the error stack. This is causing the bot to completely crash.

**Include a reproducible code sample here, if possible:**

Code doesn't really seem important here, would happen with any bot I assume.

Stack trace:

```
[BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:413
    if (!name) throw new RangeError('EMBED_FIELD_NAME');
               ^

RangeError [EMBED_FIELD_NAME]: MessageEmbed field names may not be empty.
    at Function.normalizeField ([BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:413:22)
    at [BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:435:14
    at Array.map (<anonymous>)
    at Function.normalizeFields ([BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:434:8)
    at MessageEmbed.setup ([BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:68:50)
    at new MessageEmbed ([BOT PATH]\node_modules\discord.js\src\structures\MessageEmbed.js:11:10)
    at [BOT PATH]\node_modules\discord.js\src\structures\Message.js:101:48
    at Array.map (<anonymous>)
    at Message._patch ([BOT PATH]\node_modules\discord.js\src\structures\Message.js:101:39)
    at new Message ([BOT PATH]\node_modules\discord.js\src\structures\Message.js:43:20)
    at MessageManager.add ([BOT PATH]\node_modules\discord.js\src\managers\BaseManager.js:49:32)
    at MessageManager.add ([BOT PATH]\node_modules\discord.js\src\managers\MessageManager.js:29:18)
    at MessageCreateAction.handle ([BOT PATH]\node_modules\discord.js\src\client\actions\MessageCreate.js:13:40)
    at Object.module.exports [as MESSAGE_CREATE] ([BOT PATH]\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket ([BOT PATH]\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket ([BOT PATH]\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22) {
  [Symbol(code)]: 'EMBED_FIELD_NAME'
}
```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: 12.15.0
- Operating system: Windows server 2016
- Priority this issue should have – please be realistic and elaborate if possible: P0 - Crashing internally.

### PR DESCRIPTION
**Pull request by MattIPv4**
**Please describe the changes this PR makes and why it should be merged:**

This should fix #3892 by skipping validation on embeds when they are part of a parent message.

The library works fine with this change, but per discussion in #library-discussion, we can't actually reproduce the buggy embed to test this. One should be able to assume this will work though (assuming I've added the flag in the right places) as it is disabling the validation that was throwing the error.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/MessageEmbed.js [hunk 1]
```diff
@@ -7,11 +7,19 @@ const Util = require('../util/Util');
  * Represents an embed in a message (image/video preview, rich embed, etc.)
  */
 class MessageEmbed {
-  constructor(data = {}) {
-    this.setup(data);
+  /**
+   * @param {Object} data The data to build the embed from
+   * @param {boolean} skipValidation A flag to skip field validations
```
Comment (NotSugden) [inline src/structures/MessageEmbed.js]:
```suggestion
   * @param {Object} [data={}] The data to build the embed from
   * @param {boolean} [skipValidation=false] A flag to skip field validations
```
both of these parameters are optional

File: src/structures/MessageEmbed.js [hunk 2]
```diff
@@ -65,7 +73,7 @@ class MessageEmbed {
      * The fields of this embed
      * @type {EmbedField[]}
      */
-    this.fields = data.fields ? this.constructor.normalizeFields(data.fields) : [];
+    this.fields = data.fields ? this.constructor._normalizeFields(this.skipValidation, data.fields) : [];
```
Comment (SpaceEEC) [inline src/structures/MessageEmbed.js]: Instead of making `normalizeFields` more or less a noop when skipping validation we could just revert to the previous behavior in those cases: 
https://github.com/discordjs/discord.js/blob/9c8aaf1bbcc220299e65cadb6ac54e1a7f208576/src/structures/MessageEmbed.js#L68

So, something like this:
```suggestion
    this.fields = [];
    if (data.fields) {
      this.fields = skipValidation ?
        data.fields.map(Util.cloneObject) :
        this.constructor.normalizeFields(data.fields);
    }
```

This would make all changes further down obsolete.
(And also keep this semver: patch instead of semver: minor)

File: src/structures/MessageEmbed.js [hunk 3]
```diff
@@ -7,11 +7,19 @@ const Util = require('../util/Util');
...
+  constructor(data = {}, skipValidation = false) {
+    this.setup(data, skipValidation);
   }
 
-  setup(data) {
+  /**
+   * @param {Object} data The data to build the embed from
+   * @param {boolean} skipValidation A flag to skip field validations
+   */
+  setup(data, skipValidation) {
```
Comment (SpaceEEC) [inline src/structures/MessageEmbed.js]: This method should either stay undocumented or get a docstring and a `@private`, since it's only for internal use.

File: src/structures/MessageEmbed.js (hunk 1 above)
Comment (SpaceEEC) [inline src/structures/MessageEmbed.js]: This parameter is for internal use only and should stay undocumented. (Except you can define private parameters, but I don't think you can.)

File: src/structures/MessageEmbed.js [hunk 4]
```diff
@@ -7,11 +7,19 @@ const Util = require('../util/Util');
  * Represents an embed in a message (image/video preview, rich embed, etc.)
  */
 class MessageEmbed {
-  constructor(data = {}) {
-    this.setup(data);
+  /**
+   * @param {Object} [data={}] The data to build the embed from
+   * @param {boolean} [skipValidation=false] A flag to skip field validations
```
Comment (SpaceEEC) [inline src/structures/MessageEmbed.js]: This parameter should be undocumented, since it's only for internal use.
(I don't think you can mark parameters as private, if that is possible, that would also be an option.)

File: src/structures/MessageEmbed.js (hunk 2 above)
Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: The reason I didn't want to just set `this.fields` equal to `data.fields` (more or less) is so that if `normalizeFields` got changed or expanded with more logic later on, this would still use it correctly whilst only skipping the validation part, not the whole method.

Does that make sense, or would it just be easier to set it directly and hope that no other logic gets added down the road?

File: src/structures/MessageEmbed.js (hunk 4 above)
Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: Should this param still be present in the typings, or removed there as well?

File: src/structures/MessageEmbed.js (hunk 3 above)
Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: Will remove docstring completely as this isn't in the typings.

File: src/structures/MessageEmbed.js (hunk 4 above)
Comment (SpaceEEC) [reply src/structures/MessageEmbed.js]: It should be removed there too.

Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: Ah, if we remove one param eslint get's unhappy as the method doesn't have a correct docstring. I guess the best solution is just not to have a docstring at all?

Comment (SpaceEEC) [reply src/structures/MessageEmbed.js]: I'd say so.

File: src/structures/MessageEmbed.js (hunk 2 above)
Comment (NotSugden) [reply src/structures/MessageEmbed.js]: if more logic is added later down the road this can also be changed to use that logic

Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: `normalizeFields` already has additional logic in that it makes calls to `resolveString`, which using `cloneObject` won't. I stand by my decision that we should use `normalizeFields` with a flag to skip the error throwing validation.

Comment (NotSugden) [reply src/structures/MessageEmbed.js]: if you read what space suggested, the skipValidation parameter in the constructor still exists, and Util.cloneObject is used if that is true, any data discord sends is very likely to always be a string, so there is no need to call Util.resolveString on it

Comment (NotSugden) [reply src/structures/MessageEmbed.js]: if you look at https://github.com/discordjs/discord.js/issues/3892#issuecomment-594502208 you can see that the field causing the issue does have the `name` and `value` properties, which are both strings

Comment (MattIPv4) [reply src/structures/MessageEmbed.js]: Yes, I'm aware of my own report and the issue it brings. That's not my point though -- this code had assumed that name & value will have contents. That was not the case and it broke. We should not then be making a fix that involves making other assumptions about the data, especially when there is already logic in place to handle situations that don't fit that assumption.

Comment (iCrawl) [reply src/structures/MessageEmbed.js]: I would strongly agree with space suggestion to fix this.

**Comment by MattIPv4** [comment]
Been running this fork on my bot that originally found this issue for a while now, hasn't thrown this error so I'm pretty confident this flag is working as intended.
