### PR TITLE
fix(Shard): avoid caching null child in eval/fetchClientValue

### LINKED ISSUE #4286: client/shard is null during fetchClientValues call
**Please describe the problem you are having in as much detail as possible:**

During a call to `client.shard.fetchClientValues` from one of my shards, an unhandled error is thrown internally by the library which appears to suggest one of the shards/clients is null:

```
Error [TypeError]: Cannot read property 'on' of null
    at <bot>\node_modules\discord.js\src\sharding\Shard.js:239:13
    at new Promise (<anonymous>)
    at Shard.fetchClientValue (<bot>\node_modules\discord.js\src\sharding\Shard.js:230:21)
    at ShardingManager.fetchClientValues (<bot>\node_modules\discord.js\src\sharding\ShardingManager.js:250:67)
    at Shard._handleMessage (<bot>\node_modules\discord.js\src\sharding\Shard.js:326:22)
    at ChildProcess.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  name: 'TypeError'
}
```

**Include a reproducible code sample here, if possible:**

Unable to reliably reproduce, no idea what's causing client/shard to be null.

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.10.0
- Operating system: macOS 10.14
- Priority this issue should have – please be realistic and elaborate if possible: P2 - definitely breaking but a workaround can be made for now

### PR DESCRIPTION
**Pull request by MattIPv4**
**Please describe the changes this PR makes and why it should be merged:**

This fixes #4286 by ensuring that a cached call to `eval/fetchClientValue` will never exist where both `process` and `worker` are `null` in a shard.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by MattIPv4** [comment]
An open question, should `ShardingManager#fetchClientValues` and `ShardingManager#broadcastEval` handle errors that this will throw cleanly? Currently `Promise.all` is used, so these will bubble up and cause the whole call in `ShardingManager` to error. (I think this is probably right as-is, but just wanted to check).

File: src/sharding/Shard.js [hunk 1]
```diff
@@ -225,6 +228,12 @@ class Shard extends EventEmitter {
    *   .catch(console.error);
    */
   fetchClientValue(prop) {
+    // Shard is dead (maybe respawning), don't cache anything and error immediately
+    if (!this.process && !this.worker) {
+      return new Promise((_, reject) => reject(new Error('SHARDING_NO_CHILD_EXISTS', this.id)));
```
Comment (NotSugden) [inline src/sharding/Shard.js:233]:
```suggestion
      return Promise.reject(new Error('SHARDING_NO_CHILD_EXISTS', this.id));
```

File: src/sharding/Shard.js [hunk 2]
```diff
@@ -255,6 +264,12 @@ class Shard extends EventEmitter {
    * @returns {Promise<*>} Result of the script execution
    */
   eval(script) {
+    // Shard is dead (maybe respawning), don't cache anything and error immediately
+    if (!this.process && !this.worker) {
+      return new Promise((_, reject) => reject(new Error('SHARDING_NO_CHILD_EXISTS', this.id)));
```
Comment (NotSugden) [inline src/sharding/Shard.js:269]:
```suggestion
      return Promise.reject(new Error('SHARDING_NO_CHILD_EXISTS', this.id));
```

**Review by NotSugden — CHANGES_REQUESTED** [review]
Promise.reject would be cleaner than `new Promise((_, reject) => reject(new Error(...)));

File: src/sharding/Shard.js (hunk 1 above)
Comment (MattIPv4) [reply src/sharding/Shard.js]: Ah, yes. Thanks!

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

File: src/sharding/Shard.js [hunk 3]
```diff
@@ -225,6 +228,10 @@ class Shard extends EventEmitter {
    *   .catch(console.error);
    */
   fetchClientValue(prop) {
+    // Shard is dead (maybe respawning), don't cache anything and error immediately
+    if (!this.process && !this.worker) return Promise.reject(new Error('SHARDING_NO_CHILD_EXISTS', this.id));
```
Comment (SpaceEEC) [inline src/sharding/Shard.js:232]: This error code does not seem to be defined, it should be defined in the [`Messages.js`](https://github.com/discordjs/discord.js/blob/1e63f3756e814d6b1a2a9c17af9c2b28ce37e472/src/errors/Messages.js#L5) file.

Without that it'd just throw here, which is not the intention:
https://github.com/discordjs/discord.js/blob/1e63f3756e814d6b1a2a9c17af9c2b28ce37e472/src/errors/DJSError.js#L39-L40

**Review by SpaceEEC — CHANGES_REQUESTED** [review]

File: src/sharding/Shard.js (hunk 3 above)
Comment (MattIPv4) [reply src/sharding/Shard.js:232]: Ah, didn't know it had to be defined there, some of the other errors that are thrown within Shard also aren't defined there. Will address in a bit 👍

**Review by SpaceEEC — APPROVED** [review]
