### PR TITLE
types: fix missing types for mentionable options

### LINKED ISSUE #8440: Missing types for application command mentionable options
### Which package is this bug report for?

discord.js

### Issue description

discord.js is missing respective typings for `ApplicationCommandOptionType.Mentionable`, `ApplicationCommandOptionType.Role` and `ApplicationCommandOptionType.User` in `ApplicationCommandOption`, `ApplicationCommandOptionData` and `ApplicationCommandSubCommandData`

The following interfaces are missing:
- `ApplicationCommandRoleOption`
- `ApplicationCommandUserOption`
- `ApplicationCommandMentionableOption`

_Originally posted by @Jiralite in https://github.com/discordjs/discord.js/issues/8433#issuecomment-1205323142_

### Code sample

```typescript
import { ApplicationCommandOption, ApplicationCommandOptionType } from 'discord.js'

let test: ApplicationCommandOption
if (test.type === ApplicationCommandOptionType.Role) {} // error TS2367
if (test.type === ApplicationCommandOptionType.User) {} // error TS2367
if (test.type === ApplicationCommandOptionType.Mentionable) {}  // error TS2367

// tsc
```

### Package version

discord.js@14.1.3-dev.1659614876-359f688.0

### Node.js version

node v16.13.2 + typescript 4.7.4

### Operating system

Microsoft Windows 10 Pro N 10.0.19044 Build 19044

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

### I have tested this issue on a development release

discord.js@14.1.3-dev.1659614876-359f688.0

### PR DESCRIPTION
**Pull request by janparisek**
**Please describe the changes this PR makes and why it should be merged:**
- Add `ApplicationCommandRoleOptionData` interface
- Add `ApplicationCommandRoleOption` interface
- Add `ApplicationCommandUserOptionData` interface
- Add `ApplicationCommandUserOption` interface
- Add `ApplicationCommandMentionableOptionData` interface
- Add `ApplicationCommandMentionableOption` interface
- Update `ApplicationCommandSubCommandData.options` union
- Update `ApplicationCommandOptionData` union
- Update `ApplicationCommandOption` union

Fixes #8440 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -3793,6 +3793,30 @@ export interface ApplicationCommandChannelOption extends BaseApplicationCommandO
...
+
+export interface ApplicationCommandUserOption extends BaseApplicationCommandOptionsData {
+  type: ApplicationCommandOptionType.User;
+}
+
+export interface ApplicationCommandMentionableOptionData extends BaseApplicationCommandOptionsData {
+  type: ApplicationCommandOptionType.Mentionable;
+}
+
+export interface ApplicationCommandMentionableOption extends BaseApplicationCommandData {
```
Comment (kyranet) [inline packages/discord.js/typings/index.d.ts:3816]:
```suggestion
export interface ApplicationCommandMentionableOption extends BaseApplicationCommandOptionsData {
```

**Review by kyranet — CHANGES_REQUESTED** [review]

File: packages/discord.js/typings/index.d.ts (hunk 1 above)
Comment (janparisek) [reply packages/discord.js/typings/index.d.ts]: I'm curious to know as to why a command option extends from a data type meant for commands.

I admit I'm not familar enough with d.js source code to see how this works out. Under normal circumstances, I'd have either started a discussion or rejected this request. But considering you're a maintainer of this repo, I've accepted this suggestion.

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
