### PR TITLE
types: Allow choice's value type to be strictly inferred

### LINKED ISSUE #8528: Wrong type def in ApplicationCommandOptionChoiceData.value
### Describe the bug

When I was writing my slash command today, I attempted to enter a value of a choice of 1, but then got an API error saying values can only be strings. The library allows to put numbers as well

### To Reproduce

1. Create a slash command
2. Add a choice where the value is a number.

### Screenshots

_No response_

### Device (please complete the following information)

macOS Monterrey
DiscordJS v14

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
The following code will not yield an error despite the type of the option being known:

```TypeScript
import { ApplicationCommandOptionType, ApplicationCommandType, Guild } from "discord.js"

declare const guild: Guild;

guild.commands.create({
  name: "test",
  description: "test",
  type: ApplicationCommandType.ChatInput,
  options: [
    {
      type: ApplicationCommandOptionType.String,
      name: "test",
      description: "test",
      choices: [
        {
          name: "test",
          value: 0 // No error!
        },
      ],
      required: true
    }
  ]
});
```

This pull request strengthens the types around here and resolves #8528.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -3868,27 +3868,27 @@ export interface ApplicationCommandAutocompleteStringOptionData
   autocomplete: true;
 }
 
-export interface ApplicationCommandChoicesData extends Omit<BaseApplicationCommandOptionsData, 'autocomplete'> {
+export interface ApplicationCommandChoicesData<Type> extends Omit<BaseApplicationCommandOptionsData, 'autocomplete'> {
```
Comment (imranbarbhuiya) [inline packages/discord.js/typings/index.d.ts:3871]:
```suggestion
export interface ApplicationCommandChoicesData<Type extends string | number = string | number> extends Omit<BaseApplicationCommandOptionsData, 'autocomplete'> {
```

without a default value, this is a breaking change for typings. Anyone using `ApplicationCommandChoicesData` in their code without `choice` option will get an error.

File: packages/discord.js/typings/index.d.ts [hunk 2]
```diff
@@ -3975,10 +3973,10 @@ export type ApplicationCommandOption =
   | ApplicationCommandAttachmentOption
   | ApplicationCommandSubCommand;
 
-export interface ApplicationCommandOptionChoiceData {
+export interface ApplicationCommandOptionChoiceData<Value = string | number> {
```
Comment (imranbarbhuiya) [inline packages/discord.js/typings/index.d.ts:3976]:
```suggestion
export interface ApplicationCommandOptionChoiceData<Value extends string | number = string | number> {
```

**Review by imranbarbhuiya — CHANGES_REQUESTED** [review]

**Review by imranbarbhuiya — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
Some tests for these would be nice 🙏

**Review by kyranet — APPROVED** [review]
