### PR TITLE
fix(Typing): dmChannel bulkDelete

### LINKED ISSUE #4079: DMChannel incorrectly has method bulkDelete in typings
**Please describe the problem you are having in as much detail as possible:**
The class `DMChannel` incorrectly has the method `bulkDelete` in the typings due to it inheriting all the `TextBasedChannelFields`.

**Include a reproducible code sample here, if possible:**
```ts
import {DMChannel} from 'discord.js'
declare const dmChannel: DMChannel
// no TS error
dmChannel.bulkDelete(10)
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 12.11.0
- Operating system: macOS 10.15.3
- Priority this issue should have – please be realistic and elaborate if possible: low

- [x] I have also tested the issue on latest master, commit hash: 1330e2d2

This could be easily fixed by changing the `TextBasedChannel` mixin [here](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L1967) to something like
```ts
function TextBasedChannel<T, TIgnore extends keyof TextBasedChannelFields = never>(Base?: Constructable<T>, ignore?: TIgnore[]): Constructable<T & Omit<TextBasedChannelFields, TIgnore>>;
```

and using it in [DMChannel](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L555) like this:
```ts
export class DMChannel extends TextBasedChannel(Channel, ['bulkDelete']) {
  // ...
}
```

### PR DESCRIPTION
**Pull request by DayColor**
**Please describe the changes this PR makes and why it should be merged:**
Closed #4079

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -1973,7 +1973,10 @@ declare module 'discord.js' {
 
   type Constructable<T> = new (...args: any[]) => T;
   function PartialTextBasedChannel<T>(Base?: Constructable<T>): Constructable<T & PartialTextBasedChannelFields>;
-  function TextBasedChannel<T>(Base?: Constructable<T>): Constructable<T & TextBasedChannelFields>;
+  function TextBasedChannel<T, Ignore extends keyof TextBasedChannelFields = never>(
+    Base?: Constructable<T>,
+    ignore?: Ignore[],
+  ): Constructable<T & Omit<TextBasedChannelFields, Ignore>>;
```
Comment (NotSugden) [inline typings/index.d.ts:1979]:
```suggestion
  function TextBasedChannel<T, I extends keyof TextBasedChannelFields = never>(
    Base?: Constructable<T>,
    ignore?: I[],
  ): Constructable<T & Omit<TextBasedChannelFields, I>>;
```
wouldn't it be more consistent for the type parameter to be 1 letter (also not sure if I or O for Omit would be better so leaving it as I)

Comment (DayColor) [reply typings/index.d.ts:1979]: Yeah I agree, having it to be one letter would be more consistent. Didn't think about it at the time.
