### PR TITLE
types(Message): correct `bulkDelete` return type

### LINKED ISSUE #8410: incorrect bulkDelete return type
### Which package is this bug report for?

discord.js

### Issue description

1. Bulk delete messages via ID that are not cached by the client
2. Observe `Snowflake => undefined` entries

### Code sample

```typescript
const deleted = await channel.bulkDelete([m1, m2, m3, m4], true);
console.log(deleted);
```

### Package version

14.1.1

### Node.js version

v18.7.0

### Operating system

_No response_

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by RedGuy12**
**Please describe the changes this PR makes and why it should be merged:**

Resolves #8410 (Partially)
This implements the patch fix detailed in #8410. I updated both the typings and the docs.

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Comment by vladfrangu** [comment]
Actually this is kinda redundant considering Collection#get already returns T | undefined (in this case Message | undefined) 👀

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -3658,7 +3658,7 @@ export interface TextBasedChannelFields extends PartialTextBasedChannelFields {
   bulkDelete(
     messages: Collection<Snowflake, Message> | readonly MessageResolvable[] | number,
     filterOld?: boolean,
-  ): Promise<Collection<Snowflake, Message>>;
+  ): Promise<Collection<Snowflake, Message | undefined>>;
```
Comment (Jiralite) [inline packages/discord.js/typings/index.d.ts:3661]: `PartialMessage` should be added here.

If we consider the case that a array of uncached message ids are passed to this method but we also specify the message partial, we will get back a `Message` structure but it will be partial.
