### PR TITLE
fix(Presence): account for multiple activities everywhere

### LINKED ISSUE #3695: Presence changing broken after "support for multiple activities" commit
**Please describe the problem you are having in as much detail as possible:**
After commit https://github.com/discordjs/discord.js/commit/ee0b7c155a1767ed42e2756e53d56368e8b69929 calling methods _ClientUser#setAFK_, _ClientUser#setStatus_ and _ClientUser#setPresence_ (with status) causes the client to get disconnected from the gateway with close code 4001

> [WS => Shard 0] [CLOSE]
    Event Code: 4001
    Clean: true
    Reason: Unknown opcode.

**Include a reproducible code sample here, if possible:**
```js
//any one of methods below will disconnect the client
bot.user.setAFK(true);
bot.user.setStatus("idle");
bot.user.setPresence({status: "idle"});

```

**Further details:**
- discord.js version: master
- Node.js version: 13.5.0
- Operating system: Win 10/Win server 2012
- Priority this issue should have – please be realistic and elaborate if possible: MEDIUM/HIGH - setting state is quite important I guess and it shouldn't cause the bot to get disconnected from the gateway

- [x] I have also tested the issue on latest master, commit hash: 629c57f890fc5124384ae83f74c9190c1db2dd4c

Cause of this issues seems to be this https://github.com/discordjs/discord.js/blob/6a0fe467e5f6e08360bcce0bf3039f01e6dc8678/src/structures/ClientPresence.js#L71

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes #3695 by accounting for the activities array from `Presence` in multiple places:
- Default `packet.game` to the first activity or null if none was set.
- Update example still using `activity`
- Use single activity / game if activities array is missing (for example when patching the `ClientPresence`)
- `_clone` the `activities` array
- Account for an `activities` array in `equals`

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/Presence.js [hunk 1]
```diff
@@ -89,7 +89,11 @@ class Presence {
      * The activities of this presence
      * @type {Activity[]}
      */
-    this.activities = data.activities ? data.activities.map(activity => new Activity(this, activity)) : [];
+    this.activities = data.activities ?
+      data.activities.map(activity => new Activity(this, activity)) :
+      data.game || data.activity ?
+        [new Activity(this, data.game || data.activity)] :
+        [];
```
Comment (amishshah) [inline src/structures/Presence.js]: In my opinion this is not very readable
