### PR TITLE
fix(BitField): remove for..in in favor of Object.entries

### LINKED ISSUE #3567: role.serialize() not working
The problem I'm experiencing:
When I use the method .serialize() on a role object, it returns an error.

**Include a reproducible code sample here, if possible:**
```js
let role = message.guild.roles.get("640015756657950720");
role.name
// -> shows the name of this role
role.serialize()
// -> RangeError: Invalid permission string or number.
```

**Further details:**
- discord.js version: 11.5.1 (Latest)
- Node.js version: 10.15.3
- Operating system: Windows 10
- Priority this issue should have: Low to mid

image

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes #3567 by replacing the `for..in` with an `Object.keys` making it ignore inherited properties.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/util/BitField.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ class BitField {
    */
   serialize(...hasParams) {
     const serialized = {};
-    for (const perm in this.constructor.FLAGS) serialized[perm] = this.has(perm, ...hasParams);
+    for (const flag of Object.keys(this.constructor.FLAGS)) serialized[flag] = this.has(flag, ...hasParams);
```
Comment (bdistin) [inline src/util/BitField.js]:
```suggestion
    for (const [flag, bit] of Object.entries(this.constructor.FLAGS)) serialized[flag] = this.has(bit, ...hasParams);
```
