### PR TITLE
fix: don't patch missing properties from partial payloads

### LINKED ISSUE #5605: Some values of an object extending Channel loses its value after using slash commands
I was testing the new slash command feature released about a week ago and found out an issue where there are data loss after using slash commands.
One of the Moderators in the Support Server told me it is something to do with how Discord resolves the object.

**Include a reproducible code sample here, if possible:**
```js
console.log(args[0] === "channel_id") //Text: true, Slash: true
const channel = message.guild.channels.cache.get(args[0]);
const { parentID } = channel; 
console.log(parentID) //Text: "parent_id" Slash: null
```
**Workaround**
Getting the channel using a snowflake

**Further details:**

- discord.js version: 12.5.0 (git+ssh://git@github.com/discordjs/discord.js.git#0e40f9b86826ba50aa3840807fb86e1bce6b1c3d)
- Node.js version: v14.15.3
- Operating system: Windows 10 Enterprise
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: Channel, Message, Reaction, User
- gateway intents: All
- other: N/A

Here is the screenshot for the proof:
image

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR resolves #5605 by only updating properties of Channel and subclasses when they are in the payload.
In similar vein, if a user option was used, their last message properties would reset to null. Since this is something we provide on our own, there is no reason for those to be in `_patch`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

File: src/structures/GuildChannel.js [hunk 1]
```diff
@@ -35,37 +35,47 @@ class GuildChannel extends Channel {
...
-    this.permissionOverwrites = new Collection();
-    if (data.permission_overwrites) {
-      for (const overwrite of data.permission_overwrites) {
-        this.permissionOverwrites.set(overwrite.id, new PermissionOverwrites(this, overwrite));
+    if ('permission_overwrites' in data) {
+      /**
+       * A map of permission overwrites in this channel for roles and users
+       * @type {Collection<Snowflake, PermissionOverwrites>}
+       */
+      this.permissionOverwrites = new Collection();
```
Comment (vladfrangu) [inline src/structures/GuildChannel.js:74]: This will make it be possibly undefined now, if at any point we create a channel with partial data

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]

File: src/structures/GuildChannel.js [hunk 2]
```diff
@@ -35,37 +35,48 @@ class GuildChannel extends Channel {
...
+      if (data.permission_overwrites) {
```
Comment (vladfrangu) [inline src/structures/GuildChannel.js:76]: This if check is redundant considering there's already an `in` check

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]
