### PR TITLE
fix(ReactionCollector): only call the filter function once

### LINKED ISSUE #6461: ReactionCollector filter is called twice
**Please describe the problem you are having in as much detail as possible:**
Upon adding a new reaction to a message with a `ReactionCollector` on it, the collector's filter function is called twice. This issue began with `v13.0.0`. I've checked the source code and found that the filter is called once to determine whether the `create` event should be emitted...
https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/ReactionCollector.js#L104-L106
...and again in a parent method, before emitting the `collect` event
https://github.com/discordjs/discord.js/blob/cfde127072ae06b63f17ba19b3e0d28fddef97d6/src/structures/interfaces/Collector.js#L100-L108

As a user of the library, it would be ideal if the filter function is only called once per reaction creation. In my situation, I call a third-party API in my collector's filter. The call is only intended to be placed once per reaction collection, not twice.

**Include a reproducible code sample here, if possible:**
```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

client.on('messageCreate', (msg) => {
    msg.createReactionCollector({
        filter: function(r, u) {
            console.log('in filter');   //should appear twice
            return false;
        },
    });
});

client.login("DISCORD_TOKEN");
```

**Further details:**

- discord.js version: `13.1.0`
- Node.js version: `16.6.1`
- Operating system: Windows 10 Version 21H1
- Priority this issue should have – please be realistic and elaborate if possible: Low, is not a critical problem

**Relevant client options:**

- partials: none
- gateway intents: Same as in code snippet (`GUILDS`, `GUILD_MESSAGES`, `GUILD_MESSAGE_REACTIONS`)
- other: none

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR resolved #6461 by only calling the filter function once.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/structures/ReactionCollector.js [hunk 1]
```diff
@@ -81,10 +92,10 @@ class ReactionCollector extends Collector {
    * Handles an incoming reaction for possible collection.
    * @param {MessageReaction} reaction The reaction to possibly collect
    * @param {User} user The user that added the reaction
```
Comment (vaporox) [inline src/structures/ReactionCollector.js:94]: This line should be removed (and the method signature needs to be changed in the typings too)

Comment (SpaceEEC) [reply src/structures/ReactionCollector.js:94]: I'd argue that it should just stay there: The parameter is still there, since the event emits them both.

Comment (vaporox) [reply src/structures/ReactionCollector.js:94]: It's still there for the `collect` event, but not for the `collect` method :eyes:

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
