### PR TITLE
fix(Integration): user might not be present

### LINKED ISSUE #4690: audit logs INTEGRATION_DELETE : cannot read property id
hello when im trying guild.fetchAuditLogs({type: "INTEGRATION_DELETE"}) or guild.fetchAuditLogs({type: 82}) its return

TypeError: Cannot read property 'id' of undefined

and thats all of the error 
2020-08-11T23:13:16.872330+00:00 app[worker.1]: at UserManager.add (/app/node_modules/discord.js/src/managers/BaseManager.js:45:48) 2020-08-11T23:13:16.872331+00:00 app[worker.1]: at new Integration (/app/node_modules/discord.js/src/structures/Integration.js:65:35) 2020-08-11T23:13:16.872336+00:00 app[worker.1]: at new GuildAuditLogsEntry (/app/node_modules/discord.js/src/structures/GuildAuditLogs.js:466:9) 2020-08-11T23:13:16.872336+00:00 app[worker.1]: at new GuildAuditLogs (/app/node_modules/discord.js/src/structures/GuildAuditLogs.js:164:21) 2020-08-11T23:13:16.872336+00:00 app[worker.1]: at Function.build (/app/node_modules/discord.js/src/structures/GuildAuditLogs.js:174:18) 2020-08-11T23:13:16.872336+00:00 app[worker.1]: at /app/node_modules/discord.js/src/structures/Guild.js:837:36 2020-08-11T23:13:16.872337+00:00 app[worker.1]: at runMicrotasks (<anonymous>) 2020-08-11T23:13:16.872338+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)

### PR DESCRIPTION
**Pull request by advaith1**
**Please describe the changes this PR makes and why it should be merged:**
After the recent release of application integrations (discord/discord-api-docs#1886), `user` may not be present, which causes issues as discord.js expects it to be. This PR should fix #4690, but it does not add the new features.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -889,7 +889,7 @@ declare module 'discord.js' {
     public syncedAt: number;
     public syncing: boolean;
     public type: string;
-    public user: User;
+    public user: User | null;
```
Comment (NotSugden) [inline typings/index.d.ts:892]: `user` isnt actually set to null, its just left as undefined if the user isn't present

Comment (advaith1) [reply typings/index.d.ts:892]: ah, so should this remain unchanged? I saw that Guild#premiumSubscriptionCount is typed as `number | null` but the code is like this

**Comment by advaith1** [comment]
Confirmed to fix the issue from the issue creator

File: typings/index.d.ts (hunk 1 above)
Comment (kyranet) [reply typings/index.d.ts:892]: The property isn't set when `data.user` is missing, however, you can either make the field as optional (see suggestion below), or default it to `null`.
```suggestion
    public user?: User;
```

File: typings/index.d.ts [hunk 2]
```diff
@@ -889,7 +889,7 @@ declare module 'discord.js' {
...
     public delete(reason?: string): Promise<Integration>;
     public edit(data: IntegrationEditData, reason?: string): Promise<Integration>;
     public sync(): Promise<Integration>;
```
Comment (ReelJohn) [inline typings/index.d.ts:895]: Intention is there. Will is lesser than. Can The will ap be forked then merge through time machine?
