### PR TITLE
fix(CommandInteractionOptionResolver): Handle autocompletion interactions

### LINKED ISSUE #7595: CommandInteractionOptionResolver does not behave as expected when given an AutocompleteInteraction
### Which package is this bug report for?

discord.js

### Issue description

Are there any plans to fix (*improve*) the undocumented pitfalls of autocomplete interactions?

- `CommandInteractionOptionResolver.resolved` <https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/structures/CommandInteractionOptionResolver.js#L59-L65> should be marked as nullable (per discord docs <https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure> , see `resolved`)

- Assuming the following internal state in d.js:
  ```js
  [
    { name: 'for', type: 'USER', value: '163646957783482370' },
    { name: 'action', type: 'STRING', value: 'add' },
    { name: 'product_code', type: 'STRING', value: '', focused: true }
  ]
  ```
  Fetching an option using `getUser` on an autocomplete interaction does not behave as expected.
  ```js
  autocompleteInteraction.options.getString('action') // output: 'add'; behaves as expected
  autocompleteInteraction.options.get('for').type === 'USER' // output: true; behaves as expected
  autocompleteInteraction.options.get('for').value // output: '163646957783482370'; behaves as expected
  autocompleteInteraction.options.get('for').user // output: undefined; begin head scratching
  autocompleteInteraction.options.getUser('for') // output: null; does not behave as expected since 'user' is missing from the object, this is caused by `data.data.resolved` not existing in the response send by Discord for autocomplete interactions
  ```
  Although the `USER` type is present, `getUser` does not return the expected output b/c it it missing the resolved `user` field.
(this should really be documented, I had to look at d.js source to find out why it was returning `null`)
<https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/structures/CommandInteractionOptionResolver.js#L185-L194>
  I had assumed that d.js would resolve the user id into a user under the hood when `resolved` was not present.

A lot of the head scratchers here could be resolved (pun intended) by updating the documentation or by attempting to resolve the resolvable items when discord fails to send `data.data.resolved`.

### Code sample

_No response_

### Package version

discord.js@13.6.0

### Node.js version

v16.13.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildMessages, GuildMessageReactions, DirectMessages

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
This pull request resolves #7595.

1. `ApplicationCommandOptionChoice` is not the correct return type for `CommandInteractionOptionResolver#getFocused()`. The correct type didn't seem to exist, so one was created.
2. During autocomplete interactions, `CommandInteractionOptionResolver#resolved` was `undefined`. This is now `null` and typed accordingly.
3. The `CommandInteractionOptionResolver` isn't keen on its methods returning anything for autocomplete interactions. Data was simply not sent to us. Therefore, the appropriate useless methods have been removed from the typings.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -935,7 +935,17 @@ export class AutocompleteInteraction<Cached extends CacheType = CacheType> exten
   public commandName: string;
   public commandType: ApplicationCommandType.ChatInput;
   public responded: boolean;
-  public options: Omit<CommandInteractionOptionResolver<Cached>, 'getMessage'>;
+  public options: Omit<
+    CommandInteractionOptionResolver<Cached>,
+    | 'getMessage'
+    | 'getUser'
+    | 'getAttachment'
+    | 'getBoolean'
```
Comment (SpaceEEC) [inline packages/discord.js/typings/index.d.ts:943]: Booleans do not depend on `resolved` and therefore are working fine as-is:
```suggestion
```

**Review by SpaceEEC — CHANGES_REQUESTED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
