### PR TITLE
fix(Message): avoid overwriting properties in _patch

### LINKED ISSUE #6368: Unable to get reactions on previously sent messages
**Please describe the problem you are having in as much detail as possible:**
When I try getting the reactions of a message from `<Message>.reactions.cache`, I'm left with an empty collection. I was told in the support server to open an issue if I could make it reproducible.

**Include a reproducible code sample here, if possible:**

```js
//Import Modules
const { Client, Intents, Collection } = require('discord.js');

//Create the Client
const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

//Message event
client.on('messageCreate', message => {
    //Check command
    if (message.content == "-run") {
        //Reply
        message.reply("Please react to this message with reactions I should react with.\n\nWhen you're done, say `done`.").then(emojiMessage => {
            //Collector Setup
            let filter = (m) => m.author.id == message.author.id
            collector = message.channel.createMessageCollector({ filter, time: 120 * 1000 })

            //On collect
            collector.on('collect', msg => {

                //Check content
                if (msg.content == "done") {
                    //Final reply
                    message.channel.send("Here's the reactions you sent earlier!").then(m => {
                        //Get the reactions from the message
                        let tempArray = Array.from(emojiMessage.reactions.cache.values())

                        //Prep
                        let reactionArray = []

                        //Import reactions based on name and id
                        for (let i = 0; i < tempArray.length; i++) {
                            //Check if string is emoji or not

                            //ID
                            if (containsEmojis(tempArray[i]["_emoji"].name) == false) {
                                reactionArray.push(tempArray[i]["_emoji"].id)

                                // EMOJI
                            } else {
                                reactionArray.push(tempArray[i]["_emoji"].name)
                            }
                        }

                        //React
                        for (let i = 0; i < reactionArray.length; i++) {
                            m.react(reactionArray[i])
                        }

                        console.log(reactionArray)
                        console.log(emojiMessage.reactions.cache)
                    })
                }
            })
        })
    }
})

client.login("TOKEN")
```

**Further details:**

- discord.js version: ^13.0.1
- Node.js version: v16.6.1
- Operating system: Windows 10 (64 bit) and Ubuntu Server (20.04)
- Priority this issue should have: Somewhat low, as most people get reactions via a collector, and I can modify the code to do so as well.

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS
- other: none

### LINKED ISSUE #6431: Messages lose their reaction manager when another message references them
**Please describe the problem you are having in as much detail as possible:**
When a message "X" with reactions is referenced by a different message (e.g. via reply or via fetching an old reply) , message "X" has its reaction manager overwritten and will lose access to reactions from before that point.

**Include a reproducible code sample here, if possible:**

```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

client.on('messageCreate', async message => {
    if (message.content == "?test") {
        
        /* Add 2 reactions, check they're there */
        await message.react('❤️');
        await message.react('💙');
        let reacts = message.reactions.resolve('❤️');
        console.log(reacts.me); // true
        console.log(message.reactions.cache); // Collection(2) [Map] { ❤️ and 💙 reactions }

        /* Reply to reacted-to message */
        await message.reply("This is a reply :)");

        /* Check reactions, they've disappeared. After a restart the reactions will be visible again */
        reacts = message.reactions.resolve('❤️');
        console.log(reacts?.me ?? 'Nope'); // 'Nope'
        console.log(message.reactions.cache); // Collection(0) [Map] {}

        /* React "again", this updates the reactions */
        await message.react('❤️');
        reacts = message.reactions.resolve('❤️');
        console.log(reacts.me); // true
        console.log(message.reactions.cache); // Collection(1) [Map] { ❤️ reaction }
    }
});

client.login("DISCORD_TOKEN");
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.1
- Operating system: Manjaro Linux [x86_64] (5.10.56-1-MANJARO)
- Priority this issue should have – please be realistic and elaborate if possible: Low-Medium

**Relevant client options:**

- partials: none
- gateway intents: Same as in code snippet (`GUILDS`, `GUILD_MESSAGES`, `GUILD_MESSAGE_REACTIONS`)
- other: none
- I have also tested the issue on latest main; Commit hash: `71fdf6fae0457bc5f2900a37cc2d28c587e7e54a`

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes #6431 and maybe also fixes #6368 by only updating properties if they are part of the payload.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -52,13 +52,19 @@ class Message extends Base {
     if (data) this._patch(data);
   }
 
-  _patch(data, partial = false) {
+  _patch(data) {
```
Comment (ImRodry) [inline src/structures/Message.js:55]: The typings need to be updated

File: src/structures/Message.js [hunk 2]
```diff
@@ -52,13 +52,19 @@ class Message extends Base {
...
      * The message's id
      * @type {Snowflake}
      */
     this.id = data.id;
 
+    /**
+     * The timestamp the message was sent at
+     * @type {number}
+     */
+    this.createdTimestamp = SnowflakeUtil.deconstruct(this.id).timestamp;
```
Comment (ImRodry) [inline src/structures/Message.js:66]: Why doesn't this use data.timestamp instead?

File: src/structures/Message.js [hunk 3]
```diff
@@ -339,12 +352,6 @@ class Message extends Base {
     }
   }
 
-  _update(data, partial = false) {
```
Comment (ImRodry) [inline src/structures/Message.js:342]: Typings need to be updated

File: src/structures/Message.js (hunk 2 above)
Comment (SpaceEEC) [reply src/structures/Message.js:66]: I suppose since the id is always there, that's one less thing that can break. (e.g. partial messages)

File: typings/index.d.ts [hunk 4]
```diff
@@ -1186,10 +1186,8 @@ type AwaitMessageCollectorOptionsParams<T extends MessageComponentType | Message
 
 export class Message extends Base {
   public constructor(client: Client, data: RawMessageData);
-  private _patch(data: RawPartialMessageData, partial: true): void;
-  private _patch(data: RawMessageData, partial?: boolean): void;
-  private _update(data: RawPartialMessageData, partial: true): Message;
-  private _update(data: RawMessageData, partial?: boolean): Message;
+  private _patch(data: RawPartialMessageData | RawMessageData): void;
+  private _update(data: RawPartialMessageData | RawMessageData): Message;
```
Comment (ImRodry) [inline typings/index.d.ts:1190]: Wasn't this function removed?

Comment (SpaceEEC) [reply typings/index.d.ts:1190]: It's still inherited from `Base`, which doesn't seem to have it in the types. I'll remove that line, not that it really matters.

Comment (ImRodry) [reply typings/index.d.ts:1190]: Ah I see, it should be moved there then

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.
