### PR TITLE
fix(BaseClient): Prevent user agent mutation

### LINKED ISSUE #9421: userAgentAppendix appended multiple times to REST user-agent header each time WebhookClient is instantiated
### Which package is this bug report for?

discord.js

### Issue description

The PR [#9267](https://github.com/discordjs/discord.js/pull/9267) introduced an unexpected behavior when instantiating a new WebhookClient, which extends BaseClient, specifying the `userAgentAppendix`.

Specifically, this part of the BaseClient initiation:
https://github.com/discordjs/discord.js/blob/603446a692f1e3c8299abf47d47ae8e36a0a2488/packages/discord.js/src/client/BaseClient.js#L21-L25
edits the original `options.rest.userAgentAppendix` prepending `Options.userAgentAppendix`. This is fine when instantiating a single Client, but poses problems when instantiating multiple WebhookClients after the initial initiation since the `userAgentAppendix` value gets longer and longer each time a `new WebhookClient()` is called, to the point where Discord starts returning `400` errors when sending webhooks through any newly instantiated WebhookClient.

This could be solved by deep cloning `options` before running:
https://github.com/discordjs/discord.js/blob/603446a692f1e3c8299abf47d47ae8e36a0a2488/packages/discord.js/src/client/BaseClient.js#L27-L31
and then moving the above assignment after the deep clone, applied to `this.options`, but deep cloning though JSON.parse/JSON.stringify and structuredClone breaks complex properties of the `rest` object, e.g. a custom agent.

### Code sample

```typescript
const clientOptions = { rest: { userAgentAppendix: "loremIpsum/1.0.0" } };
while (true) {
    const webhookClient = new WebhookClient({ url: "https://discord.com/api/..." }, clientOptions);
    console.log(webhookClient.options.rest.userAgentAppendix);
    // userAgentAppendix - and consequently the "user-agent" header - will progressively get bigger: discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 discord.js/14.9.0 Node.js/v18.16.0 [...] discord.js/14.9.0 Node.js/v18.16.0 loremIpsum/1.0.0
}
```

### Package version

14.9.0

### Node.js version

18.16.0

### Operating system

_No response_

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Resolves #9421 by removing the mutation (bad bad bad). We instead make use of the spread operator.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

File: packages/discord.js/src/client/BaseClient.js [hunk 1]
```diff
@@ -18,17 +18,19 @@ class BaseClient extends EventEmitter {
...
      * @type {ClientOptions}
      */
-    this.options = mergeDefault(Options.createDefault(), options);
+    this.options = mergeDefault(Options.createDefault(), {
+      ...options,
+      rest: {
+        ...options.rest,
+        userAgentAppendix: options.rest?.userAgentAppendix
+          ? `${Options.userAgentAppendix} ${options.rest.userAgentAppendix}`
+          : undefined,
```
Comment (vladfrangu) [inline packages/discord.js/src/client/BaseClient.js:31]: Shouldn't this default to `Options.userAgentAppendix` if its not provided by users?

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: packages/discord.js/src/client/BaseClient.js (hunk 1 above)
Comment (Jiralite) [reply packages/discord.js/src/client/BaseClient.js:31]: That's the whole point of `mergeDefault()`.

**Review by SpaceEEC — APPROVED** [review]
