### PR TITLE
fix(DJSError): error code validation

### LINKED ISSUE #8148: Error code must be a valid DiscordjsErrorCodes [DISALLOWED_INTENTS]
### Which package is this bug report for?

discord.js

### Issue description

Bot is crashing when encountering the error code DISALLOWED_INTENTS as it's not handled properly for MessageContent intent.

```
Error: Error code must be a valid DiscordjsErrorCodes
    at message (E:\Users\Eralyne\Documents\GitHub\striber\node_modules\discord.js\src\errors\DJSError.js:40:39)
    at new DiscordjsError (E:\Users\Eralyne\Documents\GitHub\striber\node_modules\discord.js\src\errors\DJSError.js:17:13)
    at WebSocketManager.createShards (E:\Users\Eralyne\Documents\GitHub\striber\node_modules\discord.js\src\client\websocket\WebSocketManager.js:249:15)
    at async Client.login (E:\Users\Eralyne\Documents\GitHub\striber\node_modules\discord.js\src\client\Client.js:232:7)
```

Checking out what the 'code' refers to, it returns "DisallowedIntents"

I can fix it by allowing the intent for my bot once I learned what the error code was. It just is probably beneficial to know what the error is without having to dig in the discordjs code.

### Code sample

```typescript
const { Client, GatewayIntentBits } = require("discord.js");
const client = new Client({ intents: [GatewayIntentBits.GuildVoiceStates, GatewayIntentBits.GuildMessages, GatewayIntentBits.Guilds, GatewayIntentBits.DirectMessages, GatewayIntentBits.MessageContent], partials: ["CHANNEL"] });
```

### Package version

14.0.0-dev.1655770161-94f7ca9

### Node.js version

16.15.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildVoiceStates, GuildMessages, DirectMessages, MessageContent

### I have tested this issue on a development release

65d1879

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #8148

The ws magic:tm: passes strings to the Error constructor, which then passes said string to the `message()` function, which only accepts numbers
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/client/websocket/WebSocketManager.js#L248-L249
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/errors/DJSError.js#L15-L17
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/errors/DJSError.js#L39-L40

However, the (string) error codes passed by the WS are defined
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/errors/Messages.js#L162-L167

***

To solve this, I mapped the ws error codes (because the ErrorCode keys don't always map) to djs' error codes, replacing the "ws magic" in Messages, meaning that only number error codes will be passed

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

**Comment by almeidx** [comment]
Lint is failing in /website

**Review by SpaceEEC — APPROVED** [review]

File: packages/discord.js/src/client/websocket/WebSocketManager.js [hunk 1]
```diff
@@ -22,13 +22,15 @@ const BeforeReadyWhitelist = [
...
-  GatewayCloseCodes.DisallowedIntents,
-];
+const unrecoverableErrorCodeMap = {
+  [GatewayCloseCodes.AuthenticationFailed]: ErrorCodes.TokenInvalid,
+  [GatewayCloseCodes.InvalidShard]: ErrorCodes.ShardingInvalid,
+  [GatewayCloseCodes.ShardingRequired]: ErrorCodes.ShardingRequired,
+  [GatewayCloseCodes.InvalidIntents]: ErrorCodes.InvalidIntents,
+  [GatewayCloseCodes.DisallowedIntents]: ErrorCodes.DisallowedIntents,
+};
+const UNRECOVERABLE_CLOSE_CODES = Object.keys(unrecoverableErrorCodeMap).map(k => Number(k));
```
Comment (kyranet) [inline packages/discord.js/src/client/websocket/WebSocketManager.js:32]: Instead of doing `UNRECOVERABLE_CLOSE_CODES.includes(code)`, can't we do `code in unrecoverableErrorCodeMap` or perhaps `Object.hasKey(unrecoverableErrorCodeMap, code)`?
