### PR TITLE
fix(WebSocketShard): wait a little before reconnecting

### LINKED ISSUE #9510: Infinite loop of WebSocket reconnection
### Which package is this bug report for?

ws

### Issue description

This can be reproduced with the following steps:  
1. Run the code sample.
2. Disconnect the execution environment from the Internet.
3. Observe the output log.(WebSocket tries to reconnect with unusual frequency.)
  
When I observed it, I was getting an infinite loop like this:  
1. An exception occurs in the try syntax of `WebSocketShard#waitForEvent()`.
2. `WebSocketShard#destroy()` is called within the catch syntax.
5. `WebSocketShard#internalConnect()` is called in `destroy()`.
6. `WebSocketShard#waitForEvent()` is called in `internalConnect()`.
  
This bug consumes system resources and brings the system down.

### Code sample

```typescript
import { Client, Events } from 'discord.js';

const client = new Client({ intents: ['Guilds'] });

client.on(Events.Debug, (message) => console.log(message));

client.login('DISCORD_TOKEN')
  .catch(console.error);
```

### Versions

- discord.js 14.10.2
- Node.js v18.16.0

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

14.11.0-dev.1683201849-51d53f5.0

### PR DESCRIPTION
**Pull request by didinele**
**Please describe the changes this PR makes and why it should be merged:**
Closes #9510 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by Jiralite — APPROVED** [review]

File: packages/ws/src/ws/WebSocketShard.ts [hunk 1]
```diff
@@ -259,6 +259,9 @@ export class WebSocketShard extends AsyncEventEmitter<WebSocketShardEventsMap> {
 		this.#status = WebSocketShardStatus.Idle;
 
 		if (options.recover !== undefined) {
+			// There's cases (like no internet connection) where we immediately fail to connect,
+			// causing a very fast and draining reconnection loop.
+			await sleep(500);
```
Comment (vladfrangu) [inline packages/ws/src/ws/WebSocketShard.ts:264]: I'd say let's add a debug message for this so people aren't left in the dark, but it's optional from my pov

**Review by vladfrangu — APPROVED** [review]

**Comment by didinele** [comment]
> It would be nice to be able to set the reconnection time as an option.😄

I don't see any case where that could ever be helpful

File: packages/ws/src/ws/WebSocketShard.ts (hunk 1 above)
Comment (didinele) [reply packages/ws/src/ws/WebSocketShard.ts:264]: yeah not fond, esp. given it's consistent and not all that long.

**Review by kyranet — APPROVED** [review]
