### PR TITLE
fix(WebSocketShard): handle initial connect being a resume

### LINKED ISSUE #9548: @discordjs/ws WebSocketShard#connect not resolved when resuming
### Which package is this bug report for?

ws

### Issue description

When resuming session. this doesnt seems resolved. because it waiting for ready event. https://github.com/discordjs/discord.js/blob/5b8d535fd633ff25dd801f35e13b4cb169cc42ac/packages/ws/src/ws/WebSocketShard.ts#L131

Note: this only happend when resuming at launch

### Code sample

_No response_

### Versions

@discordjs/ws@0.8.3 

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by didinele**
**Please describe the changes this PR makes and why it should be merged:**
Closes #9548 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/ws/src/ws/WebSocketShard.ts [hunk 1]
```diff
@@ -128,10 +128,28 @@ export class WebSocketShard extends AsyncEventEmitter<WebSocketShardEventsMap> {
...
+		let promise;
+
+		if (!this.initialConnectResolved) {
+			// Sleep for the remaining time, but if the connection closes in the meantime, we shouldn't wait the remainder to avoid blocking the new conn
+			promise = Promise.race([
+				once(this, WebSocketShardEvents.Ready, { signal: controller.signal }),
+				once(this, WebSocketShardEvents.Resumed, { signal: controller.signal }),
+			]);
+
+			controller.abort();
```
Comment (vladfrangu) [inline packages/ws/src/ws/WebSocketShard.ts:141]: Won't this promise reject immediately, since you abort the controller as soon as you make the promise? 👀

Comment (didinele) [reply packages/ws/src/ws/WebSocketShard.ts:141]: yea my bad, was moving stuff around and left that there

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
