### PR TITLE
fix(guild): throw if ownerId falsey

### LINKED ISSUE #7574: guild.fetchOwner() is returning a collection of guild members
### Which package is this bug report for?

discord.js

### Issue description

Using Discord 13.6.0 I am trying to get the id of the guild, is not working for me.

Trying `guild.ownerId` returns undefined, but I was then directed to try `guild.fetchOwner()`, but this returns a list of members of the guild instead of a `GuildMember`.

Looking at the Discord source code suggests that if `guild.ownerId` is undefined, this will return all the members of the guild:

``js
fetchOwner(options) {
    return this.members.fetch({ ...options, user: this.ownerId });
}
```


### Code sample

```typescript
To get the guild:


  async getGuild (guildId?: string) {
    const client = await this.getClient();
    const guildResolvable = client.guilds.resolveId(guildId || this.guildId);

    const guild = client.guilds.resolve(guildResolvable);
    if (!guild) {
      throw new Error('Unable to access guild');
    }
    return guild;
  }


This returns a guild with `ownerId` being `undefined, but then calling `guild.fetchOwner()` returns a collection of form `Collection(11) [Map] { ... }`.
```

### Package version

13.6.0

### Node.js version

16.6.0

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers, GuildMessages

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by monbrey**
Fixes #7574 and changes the method to follow our prefer-async style.

I guess it's technically breaking since the method can now throw an error where it didn't before (although it probably should have)

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by monbrey** [comment]
Just to pre-empt some expected comments:

- Yes I know ownerId isn't supposed to ever be undefined in a proper Guild object
- Yes I know the only time it probably ever is would be when you don't specify the Guilds intent
- This is still a good check and will probably become even more relevant as we shift towards the raw data storage approach

File: packages/discord.js/src/structures/Guild.js [hunk 1]
```diff
@@ -451,8 +451,12 @@ class Guild extends AnonymousGuild {
...
    * @returns {Promise<GuildMember>}
    */
-  fetchOwner(options) {
-    return this.members.fetch({ ...options, user: this.ownerId });
+  async fetchOwner(options) {
+    if (!this.ownerId) {
+      throw new Error('FETCH_OWNER_ID');
+    }
+    const member = await this.members.fetch({ ...options, user: this.ownerId });
+    return member;
```
Comment (ImRodry) [inline packages/discord.js/src/structures/Guild.js:459]: Can’t you just return this without assigning a constant and remove the await? What’s the point of this variable?

Comment (monbrey) [reply packages/discord.js/src/structures/Guild.js:459]: Making the linter happy that this isn't an async method without await.

Comment (ImRodry) [reply packages/discord.js/src/structures/Guild.js:459]: Then don’t make this an async method and return a Promise.reject

Comment (monbrey) [reply packages/discord.js/src/structures/Guild.js:459]: But we prefer async methods - I checked that internally first.

Comment (ImRodry) [reply packages/discord.js/src/structures/Guild.js:459]: Not really, most methods return a promise rejection when they don’t use the await keyword anywhere else.

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
