### PR TITLE
fix(ThreadChannel): Address parameter type on `fetchOwner()`

### LINKED ISSUE #10578: Wrong fetch options interface - ThreadChannel#fetchOwner()
### Which application is this bug report for?

Documentation

### Issue description

I opened an [issue](https://github.com/discordjs/docs/issues/13) on the wrong repo, so I'm reposting this here with more info

Original issue:
> https://discord.js.org/docs/packages/discord.js/14.16.3/ThreadChannel:Class#fetchOwner
> 
> As you can see it's
> fetchOwner(options?: [BaseFetchOptions](https://discord.js.org/docs/packages/discord.js/14.16.3/BaseFetchOptions:Interface))
> instead of
> fetchOwner(options?: [FetchThreadMemberOptions](https://discord.js.org/docs/packages/discord.js/14.16.3/FetchThreadMemberOptions:Interface))

Update w/ more info:

`Thread#fetchOwner()` returns a `ThreadMember` but with `guildMember` property `null` unless you do `Thread#fetchOwner({withMember:true})`

Turns out (according to Qjuh) that only `withMember` can be passed in options of `Thread#fetchOwner()`.  
So supposedly `FetchThreadMemberOptions` isn't still really the right one.

_Also there's no indication that you should pass this option if you don't want the member to be null (and need it to use .guildMember after 🙃)_

### Steps to Reproduce

1. Go on https://discord.js.org/docs/packages/discord.js/14.16.3/ThreadChannel:Class#fetchOwner
2. Read :)

### Versions

**Doesn't matter, it's a content related thing**
- Chrome Version 130.0.6723.69
- Updated Win 10 

### Issue priority

Low (slightly annoying)

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Resolves #10578.

In addition, this method cannot return `null`, so the typings and documentation had `null` removed (remnant of #10421).

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by didinele — APPROVED** [review]

File: packages/discord.js/src/structures/ThreadChannel.js [hunk 1]
```diff
@@ -287,11 +287,17 @@ class ThreadChannel extends BaseChannel {
     return this.parent?.permissionsFor(memberOrRole, checkAdmin) ?? null;
   }
 
+  /**
+   * Options used to fetch a thread member owner.
```
Comment (almeidx) [inline packages/discord.js/src/structures/ThreadChannel.js:291]:
```suggestion
   * Options used to fetch a thread owner.
```

**Review by almeidx — CHANGES_REQUESTED** [review]

**Review by almeidx — APPROVED** [review]
