### PR TITLE
fix(website): discord-api-types links, URL links and some minor doc issues

### LINKED ISSUE #9984: {@link StickerFormatType.Lottie} not displayed in docs
### Which application is this bug report for?

Documentation

### Issue description

https://discord.js.org/docs/packages/discord.js/14.14.1/Sticker:Class#url

is: "A link to the sticker If the sticker's format is , it returns the URL of the Lottie JSON file."
should be: "A link to the sticker If the sticker's format is Lottie, it returns the URL of the Lottie JSON file."

### Steps to Reproduce

1. Visit https://discord.js.org/docs/packages/discord.js/14.14.1/Sticker:Class#url

### Versions

- Windows 11 Enterprise 22621.2506
-  Google Chrome 119.0.6045.160

### Issue priority

Low (slightly annoying)

### PR DESCRIPTION
**Pull request by Qjuh**
**Please describe the changes this PR makes and why it should be merged:**

- fixes `@link` tags linking to discord-api-types or URL links directly not showing correctly on new docs site
- some minor doc comment issues in mainlib

supersedes #9988 
fixes #9984 

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

File: apps/website/src/components/documentation/tsdoc/TSDoc.tsx [hunk 1]
```diff
@@ -56,6 +64,24 @@ export function TSDoc({ item, tsdoc }: { readonly item: ApiItem; readonly tsdoc:
...
 
+						if (resolved && resolved.package === 'discord-api-types') {
+							const { displayName, kind, members, containerKey } = resolved.item;
+							let href = DISCORD_API_TYPES_DOCS_URL;
+
+							// dapi-types doesn't have routes for class members
+							// so we can assume this member is for an enum
+							if (kind === 'enum' && members[0]) href += `/enum/${displayName}#${members[0].displayName}`;
+							else if (kind === 'type' || kind === 'var') href += `#${displayName}`;
+							else href += `/${mapKindToMeaning(kind)}/${displayName}`;
```
Comment (Jiralite) [inline apps/website/src/components/documentation/tsdoc/TSDoc.tsx:75]: Is there no way we could consolidate this logic used in ExcerptText.tsx?

Comment (Qjuh) [reply apps/website/src/components/documentation/tsdoc/TSDoc.tsx:67]: we could make it a util function, but their used values as so different in a lot of their properties that it would become a function with many arguments but not much logic inside.

File: apps/website/src/components/documentation/tsdoc/TSDoc.tsx [hunk 2]
```diff
@@ -1,14 +1,15 @@
-import type { ApiItem } from '@discordjs/api-extractor-model';
+import { type ApiItem, ApiItemKind } from '@discordjs/api-extractor-model';
```
Comment (Jiralite) [inline apps/website/src/components/documentation/tsdoc/TSDoc.tsx:1]: Where is `ApiItemKind` being used?

**Review by Jiralite — APPROVED** [review]

File: apps/website/src/components/documentation/tsdoc/TSDoc.tsx [hunk 3]
```diff
@@ -56,6 +56,24 @@ export function TSDoc({ item, tsdoc }: { readonly item: ApiItem; readonly tsdoc:
...
 
+						if (resolved && resolved.package === 'discord-api-types') {
+							const { displayName, kind, members, containerKey } = resolved.item;
+							let href = DISCORD_API_TYPES_DOCS_URL;
+
+							// dapi-types doesn't have routes for class members
+							// so we can assume this member is for an enum
+							if (kind === 'enum' && members?.[0]) href += `/enum/${displayName}#${members[0].displayName}`;
+							else if (kind === 'type' || kind === 'var') href += `#${displayName}`;
+							else href += `/${kind}/${displayName}`;
```
Comment (iCrawl) [inline apps/website/src/components/documentation/tsdoc/TSDoc.tsx:67]:
```suggestion
							if (kind === 'enum' && members?.[0]) {
								href += `/enum/${displayName}#${members[0].displayName}`;
							} else if (kind === 'type' || kind === 'var') {
								href += `#${displayName}`;
							} else {
								href += `/${kind}/${displayName}`;
							}
```

**Review by iCrawl — APPROVED** [review]
