### PR TITLE
fix(User): set User#bot to false if not partial

### LINKED ISSUE #4702: 12.3.0 broke the User.bot property to only be `null | true` not `false | true` like in 12.2.0
**Please describe the problem you are having in as much detail as possible:**
A `User`'s `.bot` will never be false for a non-bot (unlike in v12.2.0) but it can be `null | true`.

**Include a reproducible code sample here, if possible:**
```js
%eval
const my_user_id = `163646957783482370`;
const my_user = await client.users.cache.get(my_user_id).fetch();
console.log(`my_user.bot`, my_user.bot);
// Expectation is for it to be `false` (it ends up being `null`)

const my_bot_id = `550423785795223627`;
const my_bot = await client.users.cache.get(my_bot_id).fetch();
console.log(`my_bot.bot`, my_bot.bot);
// Expectation is for it to be `true` (it meets this expectation)
```

**Further details:**
- discord.js version: 12.3.0
- Node.js version: 14.3.0
- Operating system: Windows 10
- Priority this issue should have – Moderate: this broke some of my bot after the 12.3.0 update... that's why I noticed.

**Relevant client options:**
- partials: MESSAGE, CHANNEL, REACTION
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by Vaporox**
**Please describe the changes this PR makes and why it should be merged:**

- Closes #4702 

#4636 recently introduced a bug where `User#bot` was set to `null` instead of `false`. This is the case because it checked if the bot property was present in the data to see if it was a partial or not, however this property also does not exist for a regular user. This has been fixed by using `User#partial` which checks if the username property exists instead.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by advaith1** [comment]
It's intended to be null, it being false was the bug. this pr undos the bug fix

**Comment by Vaporox** [comment]
Yes, but the current bug is that it's set to `null` even if the user is not partial instead of `false` which would be expected. Partial users still have `null` as the value for their `.bot` property

**Comment by tipakA** [comment]
But it's very similar in behavior to how API doesn't send `TextChannel.nsfw` initially, yet library sets to `false` if it is not explicitly in the payload, as was done in #4593

**Comment by almostSouji** [comment]
> It's intended to be null, it being false was the bug. this pr undos the bug fix

No, that's a misconception. The bug was introduced with the "bug fix".
If Discord does not send a field in the initial data payload which is documented to be a boolean it has to be considered false. I applied a fix to this after discussion on DAPI in #4593. The exact same principle applies to User#bot.

Now, this will lead to inconsistencies with partials, since we might falsely declare bots which we only have a partial User for as "false", however that's a caveat to swallow, imo and is regulated with "partials should be considered defunct before fetching". since the fetch then will retrieve and update the truthful `true` for the partial (but now completed) bot.

Has discord documented that anywhere? no
Is that majorly annoying, since we need to monkeypatch the API not sending data fields? yes
Should we still do it? probably

**Comment by advaith1** [comment]
Ah, I see, I assumed that it was intentional to be consistent with the API
well we should do the same thing for User#system

File: src/structures/User.js [hunk 1]
```diff
@@ -50,6 +41,13 @@ class User extends Base {
       this.username = null;
     }
 
+    /**
+     * Whether or not the user is a bot
+     * @type {?boolean}
+     * @name User#bot
+     */
+    this.bot = !this.partial ? Boolean(data.bot) : null;
```
Comment (iCrawl) [inline src/structures/User.js:49]:
```suggestion
    this.bot = Boolean(data.bot);
```

We should just revert to this and keep it that way. This is too much of a headache, if anything we should just solve this in v13/v14

**Comment by flamelessdev** [comment]
The [JSdoc for `User#bot`](https://github.com/discordjs/discord.js/blob/stable/src/structures/User.js#L44) has not been updated to account for the changes in this PR.
Unrelated to this PR, however the same issue appears to be apparent in the [JSdoc for `User#system`](https://github.com/discordjs/discord.js/blob/stable/src/structures/User.js#L44).
