### PR TITLE
fix(Message): update getters to take null permissions into account

### LINKED ISSUE #5056: Channel permissionsFor can be null
**Please describe the problem you are having in as much detail as possible:**
When using `Channel.permissionsFor`, function can return null but there is no check for that.

**Include a reproducible code sample here, if possible:**
I havn't used permissionsFor directly but used to check `Message.deleted` and received an error.
```js
TypeError: Cannot read property 'has' of null
    at Message.get deletable [as deletable] (/home/koyamie/Koya/node_modules/discord.js/src/structures/Message.js:412:69)
```
Example here: https://github.com/discordjs/discord.js/blob/master/src/structures/Message.js#L412

**Further details:**

- discord.js version: latest master commit
- Node.js version: 14.15.1
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: ['REACTION','MESSAGE']
- gateway intents: 13999
- other: none

- [x] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by zaida04**
#5056, check to make sure return from channel#permissionsFor isn't null before calling .has on it. Open to refactoring to avoid duplicate permissionsFor calls

closes #5056 

**Status**

- [] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/Message.js [hunk 1]
```diff
@@ -409,7 +409,9 @@ class Message extends Base {
     return (
       !this.deleted &&
       (this.author.id === this.client.user.id ||
-        (this.guild && this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
+        (this.guild &&
+          this.channel.permissionsFor(this.client.user) &&
+          this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
```
Comment (NotSugden) [inline src/structures/Message.js:414]: why call this twice?
wouldn't it be better to do something like
```js
const permissions = this.guild && this.channel.permissionsFor(this.client.user);
return !permissions || permissions.has(...);```

Comment (kyranet) [reply src/structures/Message.js:414]: If #5067 merges first, this line can be refactored to
```suggestion
          this.channel.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES, false) ?? false))
```

Comment (iCrawl) [reply src/structures/Message.js]: The change @kyranet mentioned can be implemented here now.

**Review by vladfrangu — APPROVED** [review]

File: src/structures/Message.js [hunk 2]
```diff
@@ -409,7 +409,7 @@ class Message extends Base {
     return (
       !this.deleted &&
       (this.author.id === this.client.user.id ||
-        (this.guild && this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
+        (this.guild && this.channel.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
```
Comment (NotSugden) [inline src/structures/Message.js:412]: this will return `undefined` if there are no permissions returned by `permissionsFor`, or alternatively return `null` if there is no guild, instead of a boolean like its meant to

**Review by NotSugden — CHANGES_REQUESTED** [review]

**Review by vladfrangu — CHANGES_REQUESTED** [review]
Need to handle reported issue first

**Comment by zaida04** [comment]
@vladfrangu resolved

File: src/structures/Message.js [hunk 3]
```diff
@@ -406,10 +406,10 @@ class Message extends Base {
    * @readonly
    */
   get deletable() {
-    return (
+    return Boolean(
       !this.deleted &&
-      (this.author.id === this.client.user.id ||
-        (this.guild && this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
+        (this.author.id === this.client.user.id ||
+          (this.guild && this.channel.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES, false))),
```
Comment (Vaporox) [inline src/structures/Message.js:412]:
```suggestion
          this.channel.permissionsFor?.(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
```
needs more optional chaining :cowboy_hat_face:

also `false` shouldnt be passed here because administrators can delete others messages

File: src/structures/Message.js [hunk 4]
```diff
@@ -406,10 +406,10 @@ class Message extends Base {
    * @readonly
    */
   get deletable() {
-    return (
+    return Boolean(
       !this.deleted &&
-      (this.author.id === this.client.user.id ||
-        (this.guild && this.channel.permissionsFor(this.client.user).has(Permissions.FLAGS.MANAGE_MESSAGES, false)))
+        (this.author.id === this.client.user.id ||
+          this.channel.permissionsFor?.(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
```
Comment (vladfrangu) [inline src/structures/Message.js:412]: When...will permissionsFor as a function be null or undefined on a channel where a message is in?
```suggestion
          this.channel.permissionsFor(this.client.user)?.has(Permissions.FLAGS.MANAGE_MESSAGES)),
```

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: src/structures/Message.js (hunk 4 above)
Comment (NotSugden) [reply src/structures/Message.js:412]: it would be undefined in a dm channel

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by NotSugden** [comment]
the same error also happens for `Message#pinnable`, which is right underneath this getter, it would make sense to include it in this PR too

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
