### PR TITLE
fix(MessageReactionAdd): prevent double messageReactionAdd triggering

### LINKED ISSUE #4284: client.on('messageReactionAdd') is firing twice for reactions added by BOTs
The 'messageReactionAdd' event fires twice for reactions added by bots

```js
client.on('messageReactionAdd', (messageReaction, user) => {
  console.log('test');
});
// 'test' logs twice in the console
// that is the only listener in all of my code for 'messageReactionAdd'
```

**Further details:**
- discord.js version: 12.2.0
- Node.js version: 14
- Operating system: Windows 10
- Priority: idk
- [] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by arthur-lchl**
**Please describe the changes this PR makes and why it should be merged:**
This fixes #4284.
The method [Message#react()](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react) calls MessageReactionAdd#handle() (`this.client.actions.MessageReactionAdd.handle()`, [line 493 at Message.js](https://github.com/discordjs/discord.js/blob/master/src/structures/Message.js#L493)). So, if the user is listening for the `messageReactionAdd` event and the bot client react using [Message#react()](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react), MessageReactionAdd#handle() method is called twice (second time when data is received from the API and handled at [WebSocketManager#handlePacket()](https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketManager.js#L370) which calls again MessageReactionAdd#handle()) and so the event` messageReactionAdd` is emitted twice (see bellow the output before PR).

I tried to fix that by doing something similar to what has been done in [MessageCreateAction#handle()](https://github.com/discordjs/discord.js/blob/master/src/client/actions/MessageCreate.js#L7).

__Example code:__
```js
require('dotenv').config()
const Discord = require('discord.js');

const client = new Discord.Client();

client.once('ready', () => console.log(`Logged in as ${client.user.tag}.`));

client.on('message', async (message) => {
  console.log('Someone said something.');
  const reaction = await message.react('🤔');
});

client.on('messageReactionAdd', (reaction, user) => {
  console.log(`${user.tag} reacted ${reaction.emoji.name} on message ${reaction.message.id}.`);
});

client.login(process.env.TOKEN);
```

__Output before PR:__
```
Logged in as Somebot#8206.
Someone said something.
Somebot#8206 reacted 🤔 on message 740631539108544752.
Somebot#8206 reacted 🤔 on message 740631539108544752.
```

__Ouput after PR:__
```
Logged in as Somebot#8206.
Someone said something.
Somebot#8206 reacted 🤔 on message 740631816695709708.
```

I also tested with partials enabled, me and the bot reacting to new and old messages, it's working.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/client/actions/MessageReactionAdd.js [hunk 1]
```diff
@@ -28,6 +28,10 @@ class MessageReactionAdd extends Action {
 
     // Verify reaction
     if (message.partial && !this.client.options.partials.includes(PartialTypes.REACTION)) return false;
+    const existing =
+      message.reactions.cache.has(data.emoji.name) &&
+      message.reactions.cache.get(data.emoji.name).users.cache.get(user.id);
```
Comment (NotSugden) [inline src/client/actions/MessageReactionAdd.js:33]: you need to account for custom emojis by using the ID

Comment (arthur-lchl) [reply src/client/actions/MessageReactionAdd.js]: you're right, fixed in 64f14cfcb6c33ad9ff4aac27862050a737a958d0

File: src/client/actions/MessageReactionAdd.js [hunk 2]
```diff
@@ -28,6 +28,12 @@ class MessageReactionAdd extends Action {
 
     // Verify reaction
     if (message.partial && !this.client.options.partials.includes(PartialTypes.REACTION)) return false;
+    const existing =
+      (message.reactions.cache.has(data.emoji.id) &&
+        message.reactions.cache.get(data.emoji.id).users.cache.get(user.id)) ||
+      (message.reactions.cache.has(data.emoji.name) &&
+        message.reactions.cache.get(data.emoji.name).users.cache.get(user.id));
+    if (existing) return { message, reaction: existing, user };
```
Comment (NotSugden) [inline src/client/actions/MessageReactionAdd.js:36]:
```suggestion
      message.reactions.cache.has(data.emoji.id || data.emoji.name) &&
      message.reactions.cache.get(data.emoji.id || data.emoji.name).users.cache.get(user.id);
    if (existing) return { message, reaction: existing, user };
```
nit

File: src/client/actions/MessageReactionAdd.js [hunk 3]
```diff
@@ -28,6 +28,10 @@ class MessageReactionAdd extends Action {
 
     // Verify reaction
     if (message.partial && !this.client.options.partials.includes(PartialTypes.REACTION)) return false;
+    const existing =
+      message.reactions.cache.has(data.emoji.id || data.emoji.name) &&
+      message.reactions.cache.get(data.emoji.id || data.emoji.name).users.cache.get(user.id);
+    if (existing) return { message, reaction: existing, user };
```
Comment (SpaceEEC) [inline src/client/actions/MessageReactionAdd.js:34]: `existing` is a `User` here, but later returned as `reaction`.

I suggest something simpler:
```suggestion
    const existing = message.reactions.cache.get(data.emoji.id || data.emoji.name)
    if (existing && existing.users.cache.has(user.id)) return { message, reaction: existing, user };
```
That way there is no `Map#has` followed by a `Map#get` and the reaction will be correctly returned.

Comment (arthur-lchl) [reply src/client/actions/MessageReactionAdd.js]: yup, you're right! Just committed your suggestion and fixed that missing semicolon 😉 
thank you!
