### PR TITLE
fix(SlashCommandBuilder): missing methods in subcommand builder

### LINKED ISSUE #8562: Property 'setDMPermission' does not exist on type 'SlashCommandSubcommandsOnlyBuilder'
### Which package is this bug report for?

discord.js

### Issue description

The image says it all. The issue is quite easily fixable by putting `.setDMPermission(false)` *before* the subcommand options, but still, Whether or not something is a slash command with subcommand options says nothing about whether or not it can be used in DMs.

image

### Code sample

```typescript
new SlashCommandBuilder()
    .setName(name)
    .setDescription(description)
    .addSubcommand(option =>
        option.setName('all')
        .setDescription('Select this if you want to store all your items away.'))
    .addSubcommand(option =>
        option.setName('custom')
        .setDescription('Select this if you want to individually store your items away.'))
    .setDMPermission(false)
```

### Package version

14.3.0

### Node.js version

v17.5.0

### Operating system

Linux Manjaro

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #8562

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by kyranet — APPROVED** [review]

File: packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts [hunk 1]
```diff
@@ -188,8 +188,7 @@ export class SlashCommandBuilder {
 export interface SlashCommandBuilder extends SharedNameAndDescription, SharedSlashCommandOptions {}
 
 export interface SlashCommandSubcommandsOnlyBuilder
-	extends SharedNameAndDescription,
-		Pick<SlashCommandBuilder, 'addSubcommand' | 'addSubcommandGroup' | 'toJSON'> {}
+	extends Omit<SlashCommandBuilder, Exclude<keyof SharedSlashCommandOptions, 'options'>> {}
```
Comment (vladfrangu) [inline packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts:191]: Does this only remove the option functions or does it keep them 👀

Comment (almeidx) [reply packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts:191]: It omits all the methods of the [`SharedSlashCommandOptions`](https://github.com/discordjs/discord.js/blob/d08a57cadd9d69a734077cc1902d931ab10336db/packages/builders/src/interactions/slashCommands/mixins/SharedSlashCommandOptions.ts#L17-L161) mixin from the [`SlashCommandBuilder`](https://github.com/discordjs/discord.js/blob/d08a57cadd9d69a734077cc1902d931ab10336db/packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts#L21-L22) class

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
