### PR TITLE
fix: censor token in debug output

### LINKED ISSUE #8763: Discord token not censored in debug output.
### Which package is this bug report for?

discord.js

### Issue description

I understand that the token is shown in the debug log, which should be disabled when the application is in production. But I noticed that the token is censored at the start of the Discord client. So perhaps censoring of the token can done in other parts of the code as well.

**Code sample contains debug log (no code).**
A censored token can be seen at the top of the file and a visible token at the bottom of the file. Sorry for the many lines (for near completeness).

**Edit:** I don't consider this a real issue but thought you may want to know.

### Code sample

```typescript
Provided token: OTAzMjQ0NDA4MjQ4NDcxNjAy.G-3V4_.**************************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 999
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 10
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] Took 11097ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 33281
[WS => Shard 0] [READY] Session 1abcd5a2bd8acd01917cd716793e1442.
[WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[WS => Shard 0] Heartbeat acknowledged, latency of 265ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 109ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 139ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.

[...]
[...]

[WS => Shard 0] Heartbeat acknowledged, latency of 118ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Tried to send packet '{"op":1,"d":71}' but no WebSocket is available!
[WS => Shard 0] [DESTROY]
    Close Code    : 4000
    Reset         : false
    Emit DESTROYED: true
[WS => Shard 0] Clearing the heartbeat interval.
[WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSING
[WS => Shard 0] WS State: CLOSING
[WS => Shard 0] Shard was destroyed but no WebSocket connection was present! Reconnecting...
[WS => Shard 0] A connection object was found. Cleaning up before continuing.
    State: CLOSING
[WS => Shard 0] [DESTROY]
    Close Code    : 1000
    Reset         : false
    Emit DESTROYED: false
[WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSING
1[WS => Shard 0] WS State: CLOSING
[WS => Shard 0] [WebSocket] Adding a WebSocket close timeout to ensure a correct WS reconnect.
        Timeout: 5000ms
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 10
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] Took 1746ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [RESUME] Session 496733fef5553759adf526f9ff7dc066, sequence 71
[WS => Shard 0] Tried to send packet '{"op":6,"d":{"token":"OTAzMjQ0NDA4MjQ4NDcxNjAy.G-3V4_.**********had-to-remove-this-myself**********","session_id":"496733fef5553759adf526f9ff7dc066","seq":71}}' but no WebSocket is available!
[WS => Shard 0] [DESTROY]
    Close Code    : 4000
    Reset         : false
    Emit DESTROYED: true
[WS => Shard 0] Clearing the heartbeat interval.
[WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSED

[...]
```

### Package version

14.5.0

### Node.js version

16.17.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #8763

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: packages/discord.js/src/client/websocket/WebSocketShard.js [hunk 1]
```diff
@@ -740,7 +740,12 @@ class WebSocketShard extends EventEmitter {
    */
   _send(data) {
     if (this.connection?.readyState !== WebSocket.OPEN) {
-      this.debug(`Tried to send packet '${JSON.stringify(data)}' but no WebSocket is available!`);
+      this.debug(
+        `Tried to send packet '${JSON.stringify(data).replaceAll(
+          this.manager.client.token,
+          this.manager.client._censoredToken,
+        )}' but no WebSocket is available!`,
+      );
```
Comment (Jiralite) [inline packages/discord.js/src/client/websocket/WebSocketShard.js:748]: Is it possible that there is no token here? Just curious, because the censored token is potentially nullable.

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
