### PR TITLE
fix(Util): throw token invalid for fetching rec. shard amount

### LINKED ISSUE #4778: Using the ShardManager, if the token is invalid, it will return an error that doesnt describe at all what is happening.
```
using ShardManager, very basic
```

**Further details:**

Returns an error:
(node:10640) UnhandledPromiseRejectionWarning: #<Response>
Running base index.js (my sharder is in sharder.js) returns invalid token error.

- discord.js version: 12.3.1
- Node.js version: 12.18.2
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: No priority

- [ ] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by almostSouji**
**Please describe the changes this PR makes and why it should be merged:**

- ⚠fixes #4778

As #4778 has brough to light we currently throw the response if an invalid token is provided when fetching the recommended amount of shards from the API.

While changing the kind of error to throw here could be framed as major i am so bold to say that this can not be deliberate design (as it results in the rather unhelpful ` #<Response>` being thrown) and thus will tag it as patch and consider it a fix rather than a feature.

https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/src/util/Util.js#L246-L247

Seeing that providing an invalid token will result in a 401 response adding a line to throw TOKEN_INVALID instead if that's the case provides more context to the user but still enables other faults to be propagated.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/util/Util.js [hunk 1]
```diff
@@ -245,7 +245,7 @@ class Util {
     })
       .then(res => {
         if (res.ok) return res.json();
-        throw res;
+        throw new DiscordError('TOKEN_INVALID');
```
Comment (NotSugden) [inline src/util/Util.js:248]: shouldn't a 5xx error be taken into account here?

Comment (almostSouji) [reply src/util/Util.js:248]: reviewing the issue again, this seems to always seems to return 401
I suppose keeping `throw res` as fallback might not be a bad idea

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
