### PR TITLE
fix(Util): splitMessage not working with array

### LINKED ISSUE #6006: Util.splitMessage can't split when char is Array
**Please describe the problem you are having in as much detail as possible:**
When Using Util.splitMessage if char is array, it not splited. it's like join ','

**Include a reproducible code sample here, if possible:**

```js
> Discord.Util.splitMessage(`${'a'.repeat('10')}\n${"b".repeat('10')}`,{maxLength: 10, char: '\n'})
[ 'aaaaaaaaaa', 'bbbbbbbbbb' ] // OK
> Discord.Util.splitMessage(`${'a'.repeat('10')}\n${"b".repeat('10')}`,{maxLength: 10, char: ['\n']})
[ 'aaaaaaaaaa,bbbbbbbbbb' ] // ??

```

**Further details:**

- discord.js version: master
- Node.js version: 14.17.1
- Operating system: Ubuntu 20.04.2
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

### PR DESCRIPTION
**Pull request by DTrombett**
fix #6006 

**Please describe the changes this PR makes and why it should be merged:**
This PR fixes a problem with Util.splitMessage which doesn't work when the `char` option is set to an array. This is because the array of messages is mapped and messages splitted again causing the creation of an array of arrays. This PR adds a `.flat(1)` to prevent this from happening. I also tested this with all options but let me know if there are still problems.

*Sorry for too many commits but I accidentally pushed the content of another PR into my master branch*

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/util/Util.js [hunk 1]
```diff
@@ -79,9 +79,9 @@ class Util {
       while (char.length > 0 && splitText.some(elem => elem.length > maxLength)) {
         const currentChar = char.shift();
         if (currentChar instanceof RegExp) {
-          splitText = splitText.map(chunk => chunk.match(currentChar));
+          splitText = splitText.map(chunk => chunk.match(currentChar)).flat(1);
```
Comment (muchnameless) [inline src/util/Util.js:82]:
```suggestion
          splitText = splitText.flatMap(chunk => chunk.match(currentChar));
```

File: src/util/Util.js [hunk 2]
```diff
@@ -79,9 +79,9 @@ class Util {
...
         } else {
-          splitText = splitText.map(chunk => chunk.split(currentChar));
+          splitText = splitText.map(chunk => chunk.split(currentChar)).flat(1);
```
Comment (muchnameless) [inline src/util/Util.js:84]:
```suggestion
          splitText = splitText.flatMap(chunk => chunk.split(currentChar));
```

File: src/util/Util.js (hunk 1 above)
Comment (DTrombett) [reply src/util/Util.js:82]: That's right lol

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
