### PR TITLE
fix: consider #nsfw false if not present in data

### LINKED ISSUE #4296: channel.nsfw returns undefined if the channel is not nsfw
Hello,i was wondering because if a channel is not nsfw it returns undefined

this is a code sample

```js
module.exports = {
	name: 'channel-info',
	execute(message, args) {
               let channel = message.guild.channels.cache.find(channel => channel.name === 'Public Channel')

               message.channel.send(`Nsfw: ${channel.nsfw}`)
		}
```

this is my code:

```js
const Discord = require('discord.js')
module.exports = {
	name: 'channel-info',
	execute(message, args) {
		if (!message.member.hasPermission('MANAGE_CHANNELS')) return message.channel.send(`${message.author.username} Non Hai Il Permesso Di Fare Il Comando __**channel-info**__`)
		
		if(!message.guild.me.hasPermission('MANAGE_CHANNELS')) return message.channel.send('Non Ho Il Permesso Di Vedere Le Informazioni Di Un Canale')

		let Nomecanale = message.content.substring(message.content.indexOf(' ')+1)

		let canale = message.guild.channels.cache.find(channel => channel.name === (Nomecanale))

		if(!canale) return message.channel.send('Canale Non Trovato')

        const channelinfo = new Discord.MessageEmbed()
	.setColor('ff0000')
	.setTitle(`Ecco Le Informazioni Del Canale: ${canale.name}`)
	.setDescription(`**Nome: ${canale.name}\nDescrizione: ${canale.topic}\nCategoria: ${canale.parent}\nTipo: ${canale.type}\nPosizione: ${canale.position}\nID: ${canale.id}\nSlowmode: ${canale.rateLimitPerUser}\nNsfw: ${canale.nsfw}\nVelocità Di Trasmissione: ${canale.bitrate}**`)
	.setTimestamp()
	.setFooter(`Comando Eseguito Da: ${message.author.username}`);
		

message.channel.send(channelinfo);
		}
	}
```

discord.js version: v12.2.0

node.js version: v12.16.2

operating system: Windows 7

### PR DESCRIPTION
**Pull request by almostSouji**
**Please describe the changes this PR makes and why it should be merged:**

- ⚠ closes #4296 

As #4296 brought up, discord.js has `text` type channels in cache where the `.nsfw` property returns `undefined`.

**Problem breakdown:**

- After some investigation the initial guess of this being caused by discord.js handling channel updates can be dismissed
- This is indeed caused by discord not sending `nsfw` in its channel data on initial guild payloads
- There are no updates sent after ready to provide these missing properties

This PR attempts to fix this inconsistency by considering the channel to not be nsfw if the `.nsfw` key is not present in the initial channel data.

<details>
<summary><b>Changes breakdown:</b></summary>

**TextChannel**

- assign `.nsfw` in the constructor with `this.nsfw = Boolean(data.nsfw);`
- patch `.nsfw` in `_patch` with `if (typeof data.nsfw !== 'undefined') this.nsfw = Boolean(data.nsfw);`
- move `.nsfw` docstring into the constructor call

**StoreChannel**

- assign `.nsfw` in the constructor with `this.nsfw = Boolean(data.nsfw);`
- patch `.nsfw` in `_patch` with `if (typeof data.nsfw !== 'undefined') this.nsfw = Boolean(data.nsfw);`
- move `.nsfw` docstring into the constructor call
- explicit constructor call due to above changes
- document constructor akin to TextChannel

</details>

<details>
<summary><b>Further considerations:</b></summary>

From my own tests (sample size: 237 channels out of which 44 are affected) i can say that after requesting said channels through the raw API endpoint `GET /channels/:id` none of the "pending" nsfw properties were `true`.

Sinister Rectus, dev of discordia could also reproduce this behavior and they seem to handle this the same way.

According to sinister this is also done on `user.bot` where we do handle this properly by assigning the `Boolean(data.bot)` in the constructor

https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/src/structures/User.js#L34

and only patching if the value is __not__ `undefined`

https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/src/structures/User.js#L61

I have applied this same reasoning to TextChannel and NewsChannel in this PR.

</details>

<details>
<summary><b>Typings considerations:</b></summary>

- Both TextChannel as well as NewsChannel are typed `boolean` instead of `?boolean` already, so this PR (fix) is consistent with the already applied typings.
- The constructor for NewsChannel has already been typed, but is now also documented accordingly

</details>

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/StoreChannel.js [hunk 1]
```diff
@@ -7,15 +7,25 @@ const GuildChannel = require('./GuildChannel');
  * @extends {GuildChannel}
  */
 class StoreChannel extends GuildChannel {
-  _patch(data) {
-    super._patch(data);
+  /**
+   * @param {*} guild The guild the store channel is part of
+   * @param {*} data The data for the store channel
```
Comment (yg) [inline src/structures/StoreChannel.js:12]: The is redundant

```suggestion
   * @param {*} guild The guild store channel is part of
   * @param {*} data The data for the store channel
```

Comment (almostSouji) [reply src/structures/StoreChannel.js:12]: It is not. "the" store channel refers to "this" store channel that's being instantiated.

"The guild store channel is part of" is not a valid sentence structure and grammatically wrong.

If anything the first "The" is redundant ("Guild the store channel is part of") however that's a library wide decision I followed for this PR
