### PR TITLE
fix(Guild): don't patch before instance properties

### LINKED ISSUE #5884: Process crashing when bot is added to a new guild
**Please describe the problem you are having in as much detail as possible:**
When the bot is added to a new guild, the process exits due to a TypeError coming from `src/structures/Guild.js` (https://sentry.io/share/issue/0092f9e524054d2e84378f1a5e3eb16a/)

**Include a reproducible code sample here, if possible:**

```ts
import { Client } from "discord.js";

const client = new Client({ intents: 1 })

client.login();

// Wait for bot to be ready then add it to a new guild
```

**Further details:**

- discord.js version: 13.0.0-dev
- Node.js version: 15.14.0 & 14.15.1
- Operating system: KDE Neon 5.22.1 & Ubuntu Server 18.04.5 LTS
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: GUILD_MEMBER, REACTION, MESSAGE, CHANNEL, USER
- gateway intents: GUILDS, GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_BANS, GUILD_INVITES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_WEBHOOKS, DIRECT_MESSAGES
- I have also tested the issue on latest master, commit hash: `1f8f3ab0f8dbd346154bbfa14a98726b8df25d57`, issue was introduced in `44e2ee7b20dbec79c993dbc1f30ddb643d943347` (#5490)

### PR DESCRIPTION
**Pull request by ckohen**
**Please describe the changes this PR makes and why it should be merged:**

When `_patch` gets called by `super()` the instance properties created after the super call don't exist yet...causing hard crashes.

fixes #5884

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -188,6 +188,7 @@ declare module 'discord.js' {
   }
 
   export abstract class AnonymousGuild extends BaseGuild {
+    constructor(client: Client, data: unknown, immediatPatch?: boolean);
```
Comment (BannerBomb) [inline typings/index.d.ts:191]:
```suggestion
    constructor(client: Client, data: unknown, immediatePatch?: boolean);
```

Comment (iShibi) [inline typings/index.d.ts:191]:
```suggestion
    constructor(client: Client, data: unknown, immediatePatch?: boolean);
```

**Review by amishshah — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
