### PR TITLE
fix(PresenceUpdate): use added presence over nullable getter

### LINKED ISSUE #6075: Bot crashes after disabling presences cache
**Please describe the problem you are having in as much detail as possible:**
I was testing the new `makeCache` option introduced in #6013 and the client crashed after disabling the presences cache (`PresenceManager: 0`) and listening to the `presenceUpdate` event. I was expecting it to be emitted with some data or partial data.

Log:
```
/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/actions/PresenceUpdate.js:30
    if (this.client.listenerCount(Events.PRESENCE_UPDATE) && member && !member.presence.equals(oldPresence)) {
                                                                                        ^

TypeError: Cannot read property 'equals' of null
    at PresenceUpdateAction.handle (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/actions/PresenceUpdate.js:30:89)
    at Object.module.exports [as PRESENCE_UPDATE] (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/websocket/handlers/PRESENCE_UPDATE.js:4:33)
    at WebSocketManager.handlePacket (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/ws/lib/websocket.js:873:20)
    at Receiver.emit (events.js:376:20)
    at Receiver.dataMessage (/media/vicente/Secundario/Desktop/Proyectos/djs-limited-caching/node_modules/ws/lib/receiver.js:517:14)
```

**Include a reproducible code sample here, if possible:**

```js
const { Client, Options } = require('discord.js')

const client = new Client({
  intents: [
    'GUILDS',
    'GUILD_MEMBERS',
    'GUILD_BANS',
    'GUILD_EMOJIS',
    'GUILD_INTEGRATIONS',
    'GUILD_WEBHOOKS',
    'GUILD_INVITES',
    'GUILD_VOICE_STATES',
    'GUILD_PRESENCES',
    'GUILD_MESSAGES',
    'GUILD_MESSAGE_REACTIONS',
    'GUILD_MESSAGE_TYPING',
    'DIRECT_MESSAGES',
    'DIRECT_MESSAGE_REACTIONS',
    'DIRECT_MESSAGE_TYPING'
  ],
  makeCache: Options.cacheWithLimits({
    PresenceManager: 0,
  }),
  partials: [
    'USER',
    'CHANNEL',
    'GUILD_MEMBER',
    'MESSAGE',
    'REACTION'
  ]
})

client.on('ready', () => {
  console.log('Bot ready')
})

client.on('presenceUpdate', (oldPresence, newPresence) => {
})

client.login(process.env.TOKEN)
```

**Further details:**

- discord.js version: `13.0.0-dev.755c180.1625659372`
- Node.js version: `14.17.0`
- Operating system: `Linux 5.4 Zorin OS 15.3`
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: Same as code sample
- gateway intents: Same as code sample
- other: `PresenceManager: 0`

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes #6075 by using the presence returned from `PresenceManager#add`.

The cause for this is a combined effort of #6013 and #6055:
The first would discard the presence on insertion (as intended when not caching them), causing the getter to return a default presence here.
With the second the default presence was removed, causing the getter to now return `null`, causing this crash.
~~I should have spotted that.~~

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by iCrawl** [comment]
This needs a rebase.

**Review by iCrawl — APPROVED** [review]

File: src/client/actions/PresenceUpdate.js [hunk 1]
```diff
@@ -26,15 +26,15 @@ class PresenceUpdateAction extends Action {
       });
       this.client.emit(Events.GUILD_MEMBER_AVAILABLE, member);
     }
-    guild.presences._add(Object.assign(data, { guild }));
-    if (this.client.listenerCount(Events.PRESENCE_UPDATE) && member && !member.presence.equals(oldPresence)) {
+    const newPresence = guild.presences._add(Object.assign(data, { guild }));
+    if (this.client.listenerCount(Events.PRESENCE_UPDATE) && newPresence.equals(oldPresence)) {
```
Comment (vaporox) [inline src/client/actions/PresenceUpdate.js:30]:
```suggestion
    if (this.client.listenerCount(Events.PRESENCE_UPDATE) && !newPresence.equals(oldPresence)) {
```
Probably got removed on accident

**Review by vladfrangu — CHANGES_REQUESTED** [review]
See vaporox's comment
