### PR TITLE
fix(GuildEmojiManager): throw an error if image resolving fails

### LINKED ISSUE #3933: Running Guild.emojis.create() without any parameters ends with the process crashing due to heap out of memory
**Please describe the problem you are having in as much detail as possible:**
While running the below code my RAM usages spikes from ~100MB to 8GB and then crashes the process with this message:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Include a reproducible code sample here, if possible:**
```js
Guild.emojis.create() // Without any parameters
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Ubuntu 18.04.4 LTS x86_64 
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes #3933. 

The method was recursing endlessly if anything falsy (such as omitting the parameter) was passed as attachment.

I moved the `DataResolver#resolveImage` call to the top of the method and made the method throw an error (`REQ_RESOURCE_TYPE`) if resolving failed.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/managers/GuildEmojiManager.js [hunk 1]
```diff
@@ -50,29 +50,30 @@ class GuildEmojiManager extends BaseManager {
...
-        for (let role of roles instanceof Collection ? roles.values() : roles) {
-          role = this.guild.roles.resolve(role);
-          if (!role) {
-            return Promise.reject(
-              new TypeError('INVALID_TYPE', 'options.roles', 'Array or Collection of Roles or Snowflakes', true),
-            );
-          }
-          data.roles.push(role.id);
+  async create(attachment, name, { roles, reason } = {}) {
+    if (typeof attachment !== 'string' || !attachment.startsWith('data:')) {
```
Comment (amishshah) [inline src/managers/GuildEmojiManager.js]: This if branch is redundant since `resolveImage` already performs these checks
