### PR TITLE
fix(WebSocketShard): buffer native zlib decompression payload

### LINKED ISSUE #10414: Unexpected end of JSON input when using `ZlibNative` & `zlib-stream` transport compression
### Which package is this bug report for?

ws

### Issue description

When using `zlib-stream` transport compression for the gateway connection in combination with `node:zlib` (`ZlibNative`) the `data` chunk returned by `node:zlib` does not contain all the JSON data resulting in a `SyntaxError` from `JSON.parse` as the data being parsed is incomplete.

The issue seems to only affect `node:zlib`, `zlib-sync` does not seem to error 

Steps to reproduce with the code below:
1. Set the `DISCORD_TOKEN` env
1. Add the `GuildMembers` privileged intent (**optional**, but it helps to make the repro consistent as it is more data discord needs to send)
1. Add the bot to a fairly big guild (lots of channels/roles/members) so that the JSON discord needs to send is more than `65535` bytes (value from the `WebSocketShard` `.internalConnect` method) https://github.com/discordjs/discord.js/blob/785ec8fd757da1d8cf7963e3cec231a6d5fe4a24/packages/ws/src/ws/WebSocketShard.ts#L201
1. Attempt to start the bot
1. If one of the guilds the bot is in was big enough the code should error with an error related to JSON parsing (the error may change based on how the chunks are splitted)

In my tests after 1/2 attempts to run the code, it will throw the error

### Code sample

```typescript
import { REST } from '@discordjs/rest'
import { CompressionMethod, SimpleShardingStrategy, WebSocketManager } from '@discordjs/ws'
import { GatewayIntentBits } from 'discord-api-types/gateway'

const token = process.env.DISCORD_TOKEN

const rest = new REST({ version: '10' })
rest.setToken(token)

const manager = new WebSocketManager({
  token,
  intents: GatewayIntentBits.Guilds | GatewayIntentBits.GuildMessages | GatewayIntentBits.GuildMembers,
  compression: CompressionMethod.ZlibNative,
  rest,
  buildStrategy(manager) {
    return new SimpleShardingStrategy(manager)
  },
})

await manager.connect()
```

### Versions

- NodeJS version: v22.5.1
- @discordjs/rest: 2.3.0
- @discordjs/ws: 2.0.0-dev.1722211862-785ec8fd7
- discord-api-types: 0.37.93
- Windows version: Windows 11 23H2, Build 22631.3958

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by didinele**
**Please describe the changes this PR makes and why it should be merged:**
Closes #10414

### CODE REVIEW

File: packages/ws/src/ws/WebSocketShard.ts [hunk 1]
```diff
@@ -626,14 +639,29 @@ export class WebSocketShard extends AsyncEventEmitter<WebSocketShardEventsMap> {
...
-				this.nativeInflate.write(decompressable, 'binary');
+				const doneWriting = new Promise<void>((resolve) => {
+					// eslint-disable-next-line promise/prefer-await-to-callbacks
+					this.nativeInflate!.write(decompressable, 'binary', (error) => {
+						if (error) {
+							this.emit(WebSocketShardEvents.Error, error);
+							resolve();
+						} else {
+							resolve();
+						}
```
Comment (almeidx) [inline packages/ws/src/ws/WebSocketShard.ts:650]:
```suggestion
						}

						resolve();
```

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]
